/*
 * frmConfigurarWorkStation.java
 *
 * Created on 26 de Setembro de 2008, 14:26
 */

package dinnamus.ui.infraestrutura;

import java.awt.event.KeyEvent;

/**
 *
 * @author  desenvolvedor
 */
public class frmConfigurarWorkStation extends javax.swing.JDialog {
    
    /** Creates new form frmConfigurarWorkStation */
    private java.awt.Frame frmPai;
    public frmConfigurarWorkStation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        frmPai=parent;
        initComponents();
       

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btImpressora = new javax.swing.JButton();
        btLoja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customizar Ambiente de Trabalho");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuração da Estação"));

        btImpressora.setMnemonic(KeyEvent.VK_I);
        btImpressora.setText("Impressora");
        btImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImpressoraActionPerformed(evt);
            }
        });

        btLoja.setMnemonic(KeyEvent.VK_L);
        btLoja.setText("Loja Atual");
        btLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLojaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btImpressora, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btImpressora, btLoja});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btImpressora, btLoja});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLojaActionPerformed
        // TODO add your handling code here:
        frmSelecionarLojaAtual frmLojaAtual=new frmSelecionarLojaAtual(frmPai, true);
        frmLojaAtual.setVisible(true);
    }//GEN-LAST:event_btLojaActionPerformed

    private void btImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImpressoraActionPerformed
        // TODO add your handling code here:
        
        frmConfigurarImpressora frmImpressora =  new frmConfigurarImpressora(frmPai, true);
        frmImpressora.setVisible(true);
    }//GEN-LAST:event_btImpressoraActionPerformed
    
    /**
     * @param args the command line arguments
     */
   
   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmConfigurarWorkStation dialog = new frmConfigurarWorkStation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImpressora;
    private javax.swing.JButton btLoja;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
