/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dinnamus.ui.infraestrutura;

import br.com.log.LogDinnamus;
import br.com.repositorio.DAO_RepositorioLocal;
import br.com.ui.MetodosUI_Auxiliares_1;
import java.sql.ResultSet;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fernando
 */
public class frmConfigImNaoFiscal extends javax.swing.JDialog {

    /**
     * Creates new form frmConfigImNaoFiscal
     */
    private boolean IniciouOK=false;
    public frmConfigImNaoFiscal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        IniciouOK=IniciarUI();
        MetodosUI_Auxiliares_1.CentrarJDialog(this, this.getToolkit());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PainelPrincipal = new javax.swing.JPanel();
        PainelTopo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();
        PainelBotoes = new javax.swing.JPanel();
        btEditarForma = new javax.swing.JButton();
        PainelCorpo = new javax.swing.JPanel();
        dbgImpressoras = new br.com.ui.JTableDinnamuS();
        PainelDados = new javax.swing.JPanel();
        lblModelo = new javax.swing.JLabel();
        txtGaveta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGuilhotina = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(566, 360));
        setMinimumSize(new java.awt.Dimension(566, 360));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PainelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PainelPrincipal.setMaximumSize(new java.awt.Dimension(566, 360));
        PainelPrincipal.setMinimumSize(new java.awt.Dimension(566, 360));
        PainelPrincipal.setLayout(new java.awt.GridBagLayout());

        PainelTopo.setBackground(new java.awt.Color(0, 0, 0));
        PainelTopo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CONFIGURAÇÃO DE IMPRESSORAS NÃO FISCAIS");
        lblTitulo.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        PainelTopo.add(lblTitulo, gridBagConstraints);

        btFechar.setBackground(new java.awt.Color(0, 0, 0));
        btFechar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ui/Shut down_16x16.png"))); // NOI18N
        btFechar.setMnemonic('x');
        btFechar.setToolTipText("");
        btFechar.setBorderPainted(false);
        btFechar.setOpaque(false);
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        btFechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btFecharKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelTopo.add(btFechar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        PainelPrincipal.add(PainelTopo, gridBagConstraints);

        PainelBotoes.setBackground(new java.awt.Color(0, 0, 0));
        PainelBotoes.setLayout(new java.awt.GridBagLayout());

        btEditarForma.setBackground(new java.awt.Color(0, 0, 0));
        btEditarForma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditarForma.setForeground(new java.awt.Color(255, 255, 255));
        btEditarForma.setMnemonic('e');
        btEditarForma.setText("GRAVAR");
        btEditarForma.setBorderPainted(false);
        btEditarForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarFormaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 23;
        PainelBotoes.add(btEditarForma, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        PainelPrincipal.add(PainelBotoes, gridBagConstraints);

        PainelCorpo.setBackground(new java.awt.Color(255, 255, 204));
        PainelCorpo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PainelCorpo.setMinimumSize(new java.awt.Dimension(0, 0));
        PainelCorpo.setPreferredSize(new java.awt.Dimension(0, 0));
        PainelCorpo.setLayout(new java.awt.GridBagLayout());

        dbgImpressoras.setPreferredSize(new java.awt.Dimension(566, 360));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        PainelCorpo.add(dbgImpressoras, gridBagConstraints);

        PainelDados.setBackground(new java.awt.Color(255, 255, 255));
        PainelDados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PainelDados.setLayout(new java.awt.GridBagLayout());

        lblModelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModelo.setText("sss");
        lblModelo.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.weighty = 0.2;
        PainelDados.add(lblModelo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelDados.add(txtGaveta, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CODIGO ACIONAR GAVETA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        PainelDados.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CODIGO ACIONAR GUILHOTINA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        PainelDados.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelDados.add(txtGuilhotina, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 5);
        PainelCorpo.add(PainelDados, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PainelPrincipal.add(PainelCorpo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(PainelPrincipal, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean IniciarUI() {
        boolean Ret = false;
        try {
           Ret = IniciarUI_dbg();
            
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        return Ret;
    }
    private boolean IniciarUI_dbg_Atualizar() {
        boolean Ret = false;
        try {
            ResultSet rs = DAO_RepositorioLocal.GerarResultSet("select * from off_modeloimpressoranaofiscal", ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            dbgImpressoras.setRsDados(rs);
            Ret=true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        return Ret;
    }
    private boolean IniciarUI_dbg() {
        boolean Ret = false;
        try {
            dbgImpressoras.addClColunas("modeloimp", "Modelo", 120);
            dbgImpressoras.addClColunas("codigoacionargaveta", "Codigo Gaveta", 200);
            dbgImpressoras.addClColunas("codigoacionarguilhotina", "Codigo Guilhotina", 200);
            dbgImpressoras.getjTable().getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                public void valueChanged(ListSelectionEvent e) {
                        
                        try {
                       
                            int Linha = dbgImpressoras.getjTable().getSelectedRow();
                            if(Linha>=0){
                                lblModelo.setText(dbgImpressoras.getTbDinnamuS().getValorCelulaString("modeloimp",Linha));
                                txtGaveta.setText(dbgImpressoras.getTbDinnamuS().getValorCelulaString("codigoacionargaveta",Linha));
                                txtGuilhotina.setText(dbgImpressoras.getTbDinnamuS().getValorCelulaString("codigoacionarguilhotina",Linha));
                            }                           
                        } catch (Exception ex) {
                            LogDinnamus.Log(ex, true);
                        }
                }
                });
            
                IniciarUI_dbg_Atualizar();
            
            Ret=true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        return Ret;
    }
    
    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        try {
            dispose();
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_btFecharActionPerformed

    private void btFecharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btFecharKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFecharKeyPressed
    private boolean ValidarRegistros() {
        boolean Ret = false;
        try {
            
            String Gaveta = txtGaveta.getText();
            Ret  = Gaveta.matches("^<[\\d{1,3}]*>");
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        return Ret;
    }
    private boolean GravarDados( String Gaveta, String Guilhotina, String ModeloImp){
        boolean Ret = false;
        try {
            
            
         Ret = DAO_RepositorioLocal.ExecutarComandoSimples("update off_modeloimpressoranaofiscal set codigoacionargaveta='"+ Gaveta +"',codigoacionarguilhotina='"+ Guilhotina  + "' where modeloimp='"+ ModeloImp +"'");
            
            
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        return Ret;
    }
    private void btEditarFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarFormaActionPerformed

        try {
            if(MetodosUI_Auxiliares_1.MensagemAoUsuarioOpcoes_Sim_e_Nao("CONFIRMA OS DADOS DA IMPRESSORA ?", "ALTERAR CONFIG DA IMPRESSORA")==MetodosUI_Auxiliares_1.Sim()){
                if(GravarDados(txtGaveta.getText(), txtGuilhotina.getText(), lblModelo.getText())){
                    MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesINFO("CONFIGURAÇÕES ALTERADOS COM SUCESSO", "CONFIG IMP. NÃO FISCAL");
                    IniciarUI_dbg_Atualizar();
                }else{
                    MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("NÃO FOI POSSÍVEL ALTERAR AS CONFIGURAÇÕES", "CONFIG IMP. NÃO FISCAL");
                }
            }
                
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
     
        

    }//GEN-LAST:event_btEditarFormaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(!IniciouOK){
            dispose();
        }else{
           // 
        }
    }//GEN-LAST:event_formWindowOpened

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelCorpo;
    private javax.swing.JPanel PainelDados;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTopo;
    private javax.swing.JButton btEditarForma;
    private javax.swing.JButton btFechar;
    private br.com.ui.JTableDinnamuS dbgImpressoras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtGaveta;
    private javax.swing.JTextField txtGuilhotina;
    // End of variables declaration//GEN-END:variables
}
