/*
 * frmGerarCFGDinnamuS.java
 *
 * Created on 12 de Agosto de 2008, 17:17
 */

package dinnamus.ui.infraestrutura;

import br.com.log.LogDinnamus;
import br.com.servidor.Dao_Jdbc_1;
import br.com.servidor.Dao_Jdbc_Base;
import br.com.ui.ItemLista;
import br.com.ui.MetodosUI_Auxiliares_1;
import br.infraestrurura.inicializacao.CriarArquivoCFG;
import br.ui.teclas.DefinirAtalhos2;
import br.ui.teclas.controleteclas;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  desenvolvedor
 */
public class frmGerarCFGDinnamuS extends javax.swing.JDialog {
    
    /** Creates new form frmGerarCFGDinnamuS */
    private Dao_Jdbc_Base cnx_master =  null;
    private boolean CarregouBanco = false;
    public frmGerarCFGDinnamuS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblCarregandoBanco.setVisible(false);
        btOK.setEnabled(false);
        lblSelecioneBanco.setEnabled(false);
        controleteclas.UsarTeclaNaTrocaDeCampos(PainelDadosServidor, KeyEvent.VK_ENTER);
        controleteclas.SetarTodosOsBotoes(this);
        //controleteclas.SetarTodosOsCombos(this);
        IniciarUI_TeclaAtalho();
    }
     private boolean IniciarUI_TeclaAtalho(){
        try {
         
            AbstractAction TeclaAtalhos  = new AbstractAction() {
                public void actionPerformed(ActionEvent e) {
                        String Fonte = e.getSource().toString();                
                        if(Fonte.equalsIgnoreCase("ESCAPE")){
                            btFechar2ActionPerformed(null);
                        }
                }
            };      
            

            String Teclas[] ={"ESCAPE"};
            
            DefinirAtalhos2.Definir(PainelPrincipal, Teclas, TeclaAtalhos);
            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        opGrupoTipoInstalacao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusuarioRepLocal = new javax.swing.JTextField();
        txtBancoRepLocal = new javax.swing.JTextField();
        txtPastaRepLocal = new javax.swing.JTextField();
        txtSenhaRepLocal = new javax.swing.JPasswordField();
        PainelPrincipal = new javax.swing.JPanel();
        subPainelPrincipal = new javax.swing.JPanel();
        btOK = new javax.swing.JButton();
        PainelCFGServidor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblSelecioneBanco = new javax.swing.JLabel();
        lblCarregandoBanco = new javax.swing.JLabel();
        cbBancos = new javax.swing.JComboBox();
        btConectar = new javax.swing.JButton();
        PainelDadosServidor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtHostServidor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUsuarioServidor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSenhaServidor = new javax.swing.JPasswordField();
        PainelTopo = new javax.swing.JPanel();
        LBLTITULO = new javax.swing.JLabel();
        btFechar2 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setText("Pasta");

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        jLabel4.setText("Banco");

        txtusuarioRepLocal.setEditable(false);
        txtusuarioRepLocal.setText("dinnamus");
        txtusuarioRepLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioRepLocalActionPerformed(evt);
            }
        });

        txtBancoRepLocal.setEditable(false);
        txtBancoRepLocal.setText("dinnamus");
        txtBancoRepLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBancoRepLocalActionPerformed(evt);
            }
        });

        txtPastaRepLocal.setEditable(false);
        txtPastaRepLocal.setText("PRINCIPAL_LOCAL");
        txtPastaRepLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPastaRepLocalActionPerformed(evt);
            }
        });

        txtSenhaRepLocal.setEditable(false);
        txtSenhaRepLocal.setText("dti");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBancoRepLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(txtusuarioRepLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSenhaRepLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPastaRepLocal))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPastaRepLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtusuarioRepLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenhaRepLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBancoRepLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 360));
        setModal(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 360));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                PreparaCargaForm(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 204));
        PainelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PainelPrincipal.setLayout(new java.awt.GridBagLayout());

        subPainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        subPainelPrincipal.setOpaque(false);
        subPainelPrincipal.setLayout(new java.awt.GridBagLayout());

        btOK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Yes.png"))); // NOI18N
        btOK.setText("CONFIRMAR");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        subPainelPrincipal.add(btOK, gridBagConstraints);

        PainelCFGServidor.setBackground(new java.awt.Color(255, 255, 255));
        PainelCFGServidor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        PainelCFGServidor.setLayout(new java.awt.GridBagLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PARAMETROS DE CONEXÃO");
        jLabel6.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.2;
        PainelCFGServidor.add(jLabel6, gridBagConstraints);

        lblSelecioneBanco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSelecioneBanco.setText("SELECIONE O BANCO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelCFGServidor.add(lblSelecioneBanco, gridBagConstraints);

        lblCarregandoBanco.setBackground(new java.awt.Color(255, 255, 255));
        lblCarregandoBanco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCarregandoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Loading_Brilho.gif"))); // NOI18N
        lblCarregandoBanco.setText("CARREGANDO BANCOS DISPONÍVEIS...AGUARDE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PainelCFGServidor.add(lblCarregandoBanco, gridBagConstraints);

        cbBancos.setEnabled(false);
        cbBancos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbBancosFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PainelCFGServidor.add(cbBancos, gridBagConstraints);

        btConectar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/redeonline.png"))); // NOI18N
        btConectar.setText("Conectar");
        btConectar.setActionCommand("");
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });
        btConectar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btConectarKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 5, 0);
        PainelCFGServidor.add(btConectar, gridBagConstraints);

        PainelDadosServidor.setBackground(new java.awt.Color(255, 255, 255));
        PainelDadosServidor.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Host");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelDadosServidor.add(jLabel10, gridBagConstraints);

        txtHostServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostServidorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        PainelDadosServidor.add(txtHostServidor, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Usuário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelDadosServidor.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelDadosServidor.add(txtUsuarioServidor, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelDadosServidor.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelDadosServidor.add(txtSenhaServidor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PainelCFGServidor.add(PainelDadosServidor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        subPainelPrincipal.add(PainelCFGServidor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(11, 7, 12, 9);
        PainelPrincipal.add(subPainelPrincipal, gridBagConstraints);

        PainelTopo.setBackground(new java.awt.Color(0, 0, 0));
        PainelTopo.setLayout(new java.awt.GridBagLayout());

        LBLTITULO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LBLTITULO.setForeground(new java.awt.Color(255, 255, 255));
        LBLTITULO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBLTITULO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/dinnamus.png"))); // NOI18N
        LBLTITULO.setText(" PDV DinnamuS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        PainelTopo.add(LBLTITULO, gridBagConstraints);

        btFechar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btFechar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Shut down_16x16.png"))); // NOI18N
        btFechar2.setMnemonic('x');
        btFechar2.setToolTipText("");
        btFechar2.setBorderPainted(false);
        btFechar2.setOpaque(false);
        btFechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechar2ActionPerformed(evt);
            }
        });
        btFechar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btFechar2KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelTopo.add(btFechar2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelPrincipal.add(PainelTopo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(PainelPrincipal, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBancoRepLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBancoRepLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBancoRepLocalActionPerformed

    private void txtusuarioRepLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioRepLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioRepLocalActionPerformed
    private boolean ValidarDados()
    {
        return ValidarDadosRepLocal() && ValidarDadosServidor();
    }
    
    private ResultSet ListarBancos(String Host, String Usuario, String Senha){
        ResultSet rs = null;
        try {
            
            Map<String,String> hmServidor=new HashMap<String, String>();            
            hmServidor.put("Host", Host);
            hmServidor.put("Banco", "master");
            hmServidor.put("Usuario", Usuario);
            hmServidor.put("Senha", Senha);
            hmServidor.put("TipoInstalacao", "PDV" );
            if(cnx_master==null){
                cnx_master= new Dao_Jdbc_Base();
            }else{
               if(cnx_master.getCNX()!=null){ 
                  cnx_master.FecharCNX();
               }
               //cnx_master=null;
            }
            if(cnx_master.getCNX()==null){
                if(!cnx_master.AbrirCnx(hmServidor)){                
                    br.com.ui.MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(cnx_master.getErro(), "SERVIDOR SQL");                    
                    return null;
                }
            }
            rs= cnx_master.GerarResultSet("select name from sysdatabases where not name in ('master','msdb','model','tempdb','northwind','pubs') order by name");              
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        return rs;
    }
    private boolean  ValidarDadosRepLocal()
    {
        boolean bRetorno=false;
        try {        
            if(txtPastaRepLocal.getText().trim().length()==0)
              JOptionPane.showMessageDialog(this, "Informe a Pasta do Repositório Local");                           
            else if(txtusuarioRepLocal.getText().trim().length()==0)
                    JOptionPane.showMessageDialog(this, "Informe o Usuário do Repositório Local");                                
            else if(txtSenhaRepLocal.getText().trim().length()==0)
                    JOptionPane.showMessageDialog(this, "Informe a Senha do Repositório Local");                            
            else if(txtBancoRepLocal.getText().trim().length()==0)
                    JOptionPane.showMessageDialog(this, "Informe o Banco do Repositório Local");                
            else
                bRetorno=true;
            } catch (Exception exception) {
                     JOptionPane.showMessageDialog(this, "Mensagem ao Operador \n" + exception.getStackTrace());                
            }
            return  bRetorno;
        }

    private boolean  ValidarDadosServidor()
    {
        boolean bRetorno=false;
        try {        
                if(txtHostServidor.getText().trim().length()==0){
                  JOptionPane.showMessageDialog(this, "Informe o nome host Servidor");                           
                   txtHostServidor.requestFocus();
                }
                else if(txtUsuarioServidor.getText().trim().length()==0){
                      JOptionPane.showMessageDialog(this, "Informe o Usuário do Servidor");                                
                      txtUsuarioServidor.requestFocus();
                }
                else if(txtSenhaServidor.getText().trim().length()==0){
                        JOptionPane.showMessageDialog(this, "Informe a Senha do Servidor");                            
                        txtSenhaServidor.requestFocus();
                }else{
                    bRetorno=true;
                }
            } catch (Exception exception) {
                     JOptionPane.showMessageDialog(this, "Mensagem ao Operador \n" + exception.getStackTrace());                
            }
            return  bRetorno;
        }
    
    private boolean ValidarBancoSelecionado(String Host, String Usuario, String Senha,String Banco){
        boolean Ret = false;
        try {
            
            Map<String,String> hmServidor=new HashMap<String, String>();            
            hmServidor.put("Host", Host);
            hmServidor.put("Banco", Banco);
            hmServidor.put("Usuario", Usuario);
            hmServidor.put("Senha", Senha);
            hmServidor.put("TipoInstalacao", "PDV" );
            Dao_Jdbc_Base cnxteste = new Dao_Jdbc_Base();
            if(cnxteste.AbrirCnx(hmServidor)){
               ResultSet rs = cnxteste.GerarResultSet("select 1 from information_schema.tables where table_name='off_configuracaoestacao'");
               if(rs!=null){
                   if(rs.next()){
                       Ret=true;
                       br.com.ui.MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("CONEXÃO VALIDADA COM SUCESSO", "CONEXÃO OK");
                   }else{
                       br.com.ui.MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("BANCO SELECIONADO NÃO PERTENCE AO DINNAMUS", "PDV - DINNAMUS : TESTANDO BANCO");
                   }
               }else{
                   br.com.ui.MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("NÃO FOI POSSÍVEL REALIZAR A VALIDAÇÃO DO BANCO SELECIONADO", "PDV - DINNAMUS : TESTANDO BANCO");
               }
               cnxteste.FecharCNX();
            }else{
                br.com.ui.MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("NÃO FOI POSSÍVEL REALIZAR A VALIDAÇÃO DO BANCO SELECIONADO", "PDV - DINNAMUS : TESTANDO BANCO");
            }
                    
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        return Ret;
    }
    private boolean  ValidarDadosCargaBancos()
    {
        //boolean bRetorno=false;
        try {        
                if(txtHostServidor.getText().trim().length()==0){
                    br.com.ui.MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("HOST NÃO INFORMADO", "CONFIGURAR PDV");
                    return false;
                }
                if(txtUsuarioServidor.getText().trim().length()==0){
                    br.com.ui.MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("USUÁRIO NÃO INFORMADO", "CONFIGURAR PDV");
                     return false;
                }
                if(txtSenhaServidor.getText().trim().length()==0){
                    br.com.ui.MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("SENHA NÃO INFORMADA", "CONFIGURAR PDV");
                   return false;
                }
            } catch (Exception exception) {
                 JOptionPane.showMessageDialog(this, "Mensagem ao Operador \n" + exception.getStackTrace());                
                 return false;
            }
            return  true;
        }

    
    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        // TODO add your handling code here:
        if(ValidarDados())
        {
            ItemLista i = (ItemLista)cbBancos.getSelectedItem();
            if(i!=null){
                if(!ValidarBancoSelecionado(txtHostServidor.getText(), txtUsuarioServidor.getText(), new String(txtSenhaServidor.getPassword()),i.getDescricao())){
                   return ;
                }
            }else{
              br.com.ui.MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("NÃO FOI POSSÍVEL SELECIONAR O BANCO","PDV DINNAMUS");
              return;
            }
           
            Map<String,Map<String,String>> hmServidores=new HashMap<String, Map<String, String>>();
            Map<String,String> hmServidor=new HashMap<String, String>();            
            Map<String,String> hmRepositorioLocal=new HashMap<String, String>();
            
            hmRepositorioLocal.put("Pasta", txtPastaRepLocal.getText());
            hmRepositorioLocal.put("Banco", txtBancoRepLocal.getText());
            hmRepositorioLocal.put("Usuario", txtusuarioRepLocal.getText());
            hmRepositorioLocal.put("Senha", new String( txtSenhaRepLocal.getPassword()));   
            
            
            hmServidor.put("Host", txtHostServidor.getText());
            hmServidor.put("Banco", i.getDescricao());
            hmServidor.put("Usuario", txtUsuarioServidor.getText());
            hmServidor.put("Senha", txtSenhaServidor.getText());
            hmServidor.put("TipoInstalacao", "PDV" );
                        
            hmServidores.put("Servidor1", hmServidor);

            boolean bAbrirCNX=Dao_Jdbc_1.getConexao().AbrirCnx(hmServidor);
            //Dao_Jdbc.getConexao().setPontoDeSalvamento(null);
            if(bAbrirCNX)
            {
                Dao_Jdbc_1.getConexao().FecharCNX();
                if(CriarArquivoCFG.Criar(hmRepositorioLocal,hmServidores))
                {
                   JOptionPane.showMessageDialog(this, "Arquivo de configuração criado com sucesso");
                   cbBancos.removeAllItems();
                   btOK.setEnabled(false);
                   this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(this, "Não foi possível criar o  Arquivo de configuração");
            }
            else
            {
                MetodosUI_Auxiliares_1.MensagemAoUsuarioSimples(new JFrame(), "Configuração inválida. Verificar os dados da conexão", "Configurador de Conexão", "AVISO");

            }
             
                
        }
    }//GEN-LAST:event_btOKActionPerformed

    private void PreparaCargaForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PreparaCargaForm
        // TODO add your handling code here:
        //lblMsg.setText(VerificarArquivoCFG.getMensagemAOUsuario());
        txtHostServidor.requestFocus();
        
      
    }//GEN-LAST:event_PreparaCargaForm

    private void txtPastaRepLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPastaRepLocalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtPastaRepLocalActionPerformed

private void CarregarComboBancos(){    
    try{
           // if(!CarregouBanco){
                if(ValidarDadosCargaBancos()){
                    //cbBancos.setEnabled(false);
                    new Thread(){
                        @Override
                        public void run() {
                                lblSelecioneBanco.setEnabled(false);
                                btOK.setEnabled(false);
                                cbBancos.setEnabled(false); 
                                boolean ret= CarregarBancos();
                                lblSelecioneBanco.setEnabled(ret);
                                btOK.setEnabled(ret);
                                cbBancos.setEnabled(ret);                                                                
                                
                        }                    
                    }.start();
                }
           // }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
}
private boolean CarregarBancos(){
        boolean Ret = false;
        lblSelecioneBanco.setVisible(false);
        lblCarregandoBanco.setVisible(true);
        
        try 
        {
            ResultSet rs = ListarBancos(txtHostServidor.getText(), txtUsuarioServidor.getText(), new String(txtSenhaServidor.getPassword()));
            if(rs!=null){
               Ret = MetodosUI_Auxiliares_1.PreencherCombo(cbBancos, rs,"name","name",true);
               Ret=true;
            }else{
                cbBancos.removeAllItems();
            }
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        lblCarregandoBanco.setVisible(false);
        lblSelecioneBanco.setVisible(true);
        return Ret;
    }
    private void btFechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechar2ActionPerformed
        try {          
            System.exit(0);
            //dispose();
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_btFechar2ActionPerformed

    private void btFechar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btFechar2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFechar2KeyPressed

    private void cbBancosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbBancosFocusGained
        // TODO add your handling code here:
                
    }//GEN-LAST:event_cbBancosFocusGained

    private void txtHostServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHostServidorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtHostServidorActionPerformed

    private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectarActionPerformed
        // TODO add your handling code here:
        CarregarComboBancos();
    }//GEN-LAST:event_btConectarActionPerformed

    private void btConectarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btConectarKeyPressed
        // TODO add your handling code here:
    if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            btConectarActionPerformed(null);
        }
    }//GEN-LAST:event_btConectarKeyPressed
        
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLTITULO;
    private javax.swing.JPanel PainelCFGServidor;
    private javax.swing.JPanel PainelDadosServidor;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTopo;
    private javax.swing.JButton btConectar;
    private javax.swing.JButton btFechar2;
    private javax.swing.JButton btOK;
    private javax.swing.JComboBox cbBancos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblCarregandoBanco;
    private javax.swing.JLabel lblSelecioneBanco;
    private javax.swing.ButtonGroup opGrupoTipoInstalacao;
    private javax.swing.JPanel subPainelPrincipal;
    private javax.swing.JTextField txtBancoRepLocal;
    private javax.swing.JTextField txtHostServidor;
    private javax.swing.JTextField txtPastaRepLocal;
    private javax.swing.JPasswordField txtSenhaRepLocal;
    private javax.swing.JPasswordField txtSenhaServidor;
    private javax.swing.JTextField txtUsuarioServidor;
    private javax.swing.JTextField txtusuarioRepLocal;
    // End of variables declaration//GEN-END:variables
    
}
