/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCaixaDisponiveis.java
 *
 * Created on 29/08/2010, 00:19:30
 */

package dinnamus.ui.InteracaoUsuario.Venda;

import br.com.info.Sistema;
import br.com.log.LogDinnamus;
import MetodosDeNegocio.Seguranca.UsuarioSistema;
import br.com.repositorio.DAO_RepositorioLocal;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author dti
 */
public class frmCaixaDisponiveis extends javax.swing.JDialog {

    /** Creates new form frmCaixaDisponiveis */
    public frmCaixaDisponiveis(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if(InicializarUI())
        {
            //dbgCaixa.requestFocus();
            this.setLocationRelativeTo(null);
            try {
                dbgCaixa.getRsDados().beforeFirst();
                if (!dbgCaixa.getRsDados().next()) {
                    this.dispose();
                } else {
                    
                    
                    this.dbgCaixa.getjTable().requestFocus();
                    if(this.dbgCaixa.getjTable().getRowCount()>0){
                        this.dbgCaixa.getjTable().setRowSelectionInterval(0, 0);
                    }
                    this.update(this.getGraphics());
                    this.setVisible(true);                    
                }
            } catch (SQLException ex) {
               LogDinnamus.Log(ex);
            }
            
        }
        else
        {
            this.dispose();
        }
    }
    protected boolean InicializarUI()
    {
        boolean bRet=false;

        try {
            String cSql="select c.codigo CodCaixa, c.nome as Caixa, u.Codigo as CodigoUs , u.nome Usuario " +
	  "from caixas c " +
		"inner join usuario u " +
			"on u.codigo=c.operadorcx " +
                "inner join filial f "+
                " on f.codigofilial=c.filial " +
            "where c.status='A' and f.codigoloja=" + Sistema.getCodigoLojaMatriz();
            dbgCaixa.getjTable().getTableHeader().setResizingAllowed(false);
            dbgCaixa.getjTable().getTableHeader().setReorderingAllowed(false);            
            dbgCaixa.setRsDados( DAO_RepositorioLocal.GerarResultSet(cSql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY));
            dbgCaixa.TamanhoColunas(new int[] {50,200,50,200});
            dbgCaixa.update(dbgCaixa.getGraphics());
            dbgCaixa.getjTable().addKeyListener(
            new KeyListener() {
                public void keyTyped(KeyEvent e) {
                    if(e.getKeyChar()=='\n')
                    {
                        //SelecionarCaixa(dbgCaixa.TratarLinhaSelecionada(dbgCaixa.getjTable()));
                        btAbrirActionPerformed(null);
                        e.consume();
                    }
                }
                public void keyPressed(KeyEvent e) {
                if(e.getKeyCode()==KeyEvent.VK_ENTER )
                    e.consume();
                }
                public void keyReleased(KeyEvent e) {}
                }
            );

            bRet=true;
        } catch (Exception e) {
            LogDinnamus.Log(e);
        }

        return bRet;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbgCaixa = new br.com.ui.JTableDinnamuS();
        jPanel1 = new javax.swing.JPanel();
        btAbrir = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caixas Disponíveis");

        dbgCaixa.setExibirBarra(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btAbrir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAbrir.setMnemonic('E');
        btAbrir.setText("Escolher Caixa");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        btFechar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFechar.setMnemonic('F');
        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAbrir, btFechar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btFechar))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAbrir, btFechar});

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(212, 208, 200));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Escolha um Caixa para Acessar as funções do PDV");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addComponent(dbgCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbgCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        // TODO add your handling code here:
        if(SelecionarCaixa(dbgCaixa.TratarLinhaSelecionada(dbgCaixa.getjTable())))
        {
          this.dispose();
        }
    }//GEN-LAST:event_btAbrirActionPerformed
    protected boolean SelecionarCaixa(Object[] LinhaSelecionada)
    {
        boolean bRet=false;
        try {
            //Object[] LinhaSelecionada= dbgCaixa.TratarLinhaSelecionada(dbgCaixa.getjTable());
            if(LinhaSelecionada!=null)
            {
                UsuarioSistema.setIdCaixaAtual(Integer.valueOf(LinhaSelecionada[0].toString()));
                UsuarioSistema.setIdUsuarioLogadoCaixa(Integer.valueOf(LinhaSelecionada[2].toString()));
                bRet=true;
            }
        } catch (Exception e) {
            LogDinnamus.Log(e);
        }
        return bRet;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCaixaDisponiveis dialog = new frmCaixaDisponiveis(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btFechar;
    private br.com.ui.JTableDinnamuS dbgCaixa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
