/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dinnamus.ui.InteracaoUsuario.Venda;

import br.TratamentoNulo.TratamentoNulos;
import br.com.log.LogDinnamus;
import br.ui.teclas.TeclasDeAtalho;
import br.com.FormatarNumeros;
import br.com.info.Sistema;
import br.com.repositorio.DAO_RepositorioLocal;
import br.com.ui.MetodosUI_Auxiliares_1;
import MetodosDeNegocio.Venda.Troca;
import MetodosDeNegocio.Venda.VendaEmEdicao;
import java.awt.Robot;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.AbstractAction;
import javax.swing.Action;

/**
 *
 * @author Fernando
 */
public class frmPDV_SimplesSelecionarTroca extends javax.swing.JDialog {

    /**
     * Creates new form frmPDV_SimplesDesconto
     */
    private boolean PreVenda  = false;
    private Double SaldoFinal=0d;
    public boolean TrocaOK=false;        
    public Double CreditoTroca =0d;
    public Long CodigoTroca = 0l;
    public Long CodigoVenda  = 0l;
    public Long CodigoUsuario = 0l;
    private boolean bActiveForm = false;
    private boolean IniciouOK = false;
    private String TipoComprovante = "";
    private boolean FecharForm = false;
    public frmPDV_SimplesSelecionarTroca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        //btCancelarTroca.setVisible(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PainelPrincipal = new javax.swing.JPanel();
        PainelCorpo = new javax.swing.JPanel();
        btGravarDesconto = new javax.swing.JButton();
        PainelCreditoTroca = new javax.swing.JPanel();
        txtValorCreditoTroca = new javax.swing.JFormattedTextField();
        PainelBotoesTroca = new javax.swing.JPanel();
        btCancelarTroca = new javax.swing.JButton();
        btTroca = new javax.swing.JButton();
        PainelTopo = new javax.swing.JPanel();
        btFechar2 = new javax.swing.JButton();
        lblTituloForm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(383, 260));
        setMinimumSize(new java.awt.Dimension(383, 260));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(383, 260));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 204));
        PainelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PainelPrincipal.setLayout(new java.awt.GridBagLayout());

        PainelCorpo.setBackground(new java.awt.Color(255, 255, 255));
        PainelCorpo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PainelCorpo.setLayout(new java.awt.GridBagLayout());

        btGravarDesconto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btGravarDesconto.setMnemonic('O');
        btGravarDesconto.setText("OK");
        btGravarDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarDescontoActionPerformed(evt);
            }
        });
        btGravarDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btGravarDescontoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelCorpo.add(btGravarDesconto, gridBagConstraints);

        PainelCreditoTroca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ( - ) CRÉDITO DE TROCA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PainelCreditoTroca.setOpaque(false);
        PainelCreditoTroca.setLayout(new java.awt.GridBagLayout());

        txtValorCreditoTroca.setEditable(false);
        txtValorCreditoTroca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txtValorCreditoTroca.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorCreditoTroca.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtValorCreditoTroca.setValue(0f);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        PainelCreditoTroca.add(txtValorCreditoTroca, gridBagConstraints);

        PainelBotoesTroca.setOpaque(false);
        PainelBotoesTroca.setLayout(new java.awt.GridBagLayout());

        btCancelarTroca.setBackground(new java.awt.Color(0, 0, 0));
        btCancelarTroca.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCancelarTroca.setForeground(new java.awt.Color(255, 255, 255));
        btCancelarTroca.setText("CANCELAR TROCA - [F6]");
        btCancelarTroca.setBorderPainted(false);
        btCancelarTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarTrocaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        PainelBotoesTroca.add(btCancelarTroca, gridBagConstraints);

        btTroca.setBackground(new java.awt.Color(0, 0, 0));
        btTroca.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btTroca.setForeground(new java.awt.Color(255, 255, 255));
        btTroca.setText("DIGITAR TROCA - [F5]");
        btTroca.setBorderPainted(false);
        btTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrocaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        PainelBotoesTroca.add(btTroca, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 13, 0);
        PainelCreditoTroca.add(PainelBotoesTroca, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PainelCorpo.add(PainelCreditoTroca, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 14, 10);
        PainelPrincipal.add(PainelCorpo, gridBagConstraints);

        PainelTopo.setBackground(new java.awt.Color(51, 51, 51));
        PainelTopo.setLayout(new java.awt.GridBagLayout());

        btFechar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btFechar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Shut down_16x16.png"))); // NOI18N
        btFechar2.setMnemonic('x');
        btFechar2.setToolTipText("");
        btFechar2.setBorderPainted(false);
        btFechar2.setOpaque(false);
        btFechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechar2ActionPerformed(evt);
            }
        });
        btFechar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btFechar2KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.2;
        PainelTopo.add(btFechar2, gridBagConstraints);

        lblTituloForm.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloForm.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloForm.setText(" PDV - TROCA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PainelTopo.add(lblTituloForm, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelPrincipal.add(PainelTopo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(PainelPrincipal, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean setValorFinal(){
        try {
          
            Float nCreditoTroca =  (Float)txtValorCreditoTroca.getValue();
            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }       
  
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(!IniciouOK || FecharForm){
            dispose();
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btFechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechar2ActionPerformed
        dispose();

    }//GEN-LAST:event_btFechar2ActionPerformed

    private void btFechar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btFechar2KeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_btFechar2KeyPressed
    private boolean AcionarTroca(){
        try {            
            Double SaldoDevedor = this.SaldoFinal;
            //Float ValorCreditoTroca =0f;            
            frmPDV_SimplesTroca troca = new frmPDV_SimplesTroca(null, true, Sistema.CodigoDaFilial_LojaAtual(), this.CodigoTroca, this.CodigoVenda ,false,SaldoDevedor,(TipoComprovante.equalsIgnoreCase("fiscal") ? true : false),PreVenda);
            troca.setVisible(true);            
            if(troca.CodigoTroca>0l){
               if(VendaEmEdicao.RegistrarVendaEmEdicao_AtualizarDados(this.CodigoVenda, null, null, null, null, null, troca.ValorCreditoTroca, troca.CodigoTroca,null,null,null,null)){
                    DAO_RepositorioLocal.Commitar_Statment();
                    this.CodigoTroca =troca.CodigoTroca;
                    this.CreditoTroca = troca.ValorCreditoTroca;
                    //txtCodigoTroca.setText(CodigoTroca.toString());                 
                    txtValorCreditoTroca.setValue( this.CreditoTroca );
                    //setValorFinal();
                    TrocaOK=true;
                    btFechar2ActionPerformed(null);//dispose();
               }               
            }
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
     public boolean CarregarInterface(String TipoComprovante,  Long CodigoVenda, Long CodigoUsuario, Double ValorFinal, Double ValorCredito, Long CodigoTrocaSelecionada, boolean  PreVenda){
        try {
           
           
           //Float ValorVendaForm = ValorVendaPDV;//FormatarNumero.FormatarNumero(txtValorVenda.getValue().toString());          
            this.PreVenda = PreVenda;
            
           if(!IniciarUI()){
               MetodosUI_Auxiliares_1.MensagemAoUsuarioSimples(null, "Não foi possível iniciar a UI de desconto e/ou acrescimo", "PDV Desconto", "AVISO");
               return false;
           }          
           
           this.SaldoFinal = ValorFinal;
           this.CreditoTroca = ValorCredito;
           this.CodigoTroca =CodigoTrocaSelecionada;
           btGravarDesconto.setEnabled(true);
           this.TipoComprovante = TipoComprovante;
           this.CodigoVenda = CodigoVenda;          
           txtValorCreditoTroca.setValue(ValorCredito);
           IniciouOK=true;
           FecharForm=false;
           if(this.CodigoTroca==0l){
              AcionarTroca();
              (new Robot()).keyPress(KeyEvent.VK_ESCAPE);
               
           }
           return true;
           
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            IniciouOK=false;
            return false;            
         
        }
    }
    private void btTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrocaActionPerformed
        // TODO add your handling code here:
        if(!btTroca.isVisible()){
            return;
        }
        AcionarTroca();
        
    }//GEN-LAST:event_btTrocaActionPerformed
//    }else{
  //                       
    private boolean PesquisarCodigoTroca(){
        try {
           /* if(txtCodigoTroca.getText().length()>0){
                if(!txtCodigoTroca.getText().equalsIgnoreCase("0")){
                    if(PesquisarCodigoTroca_Acao()){
                        AtualizarCamposUI();
                    }else{
                        txtCodigoTroca.setText("0");
                        txtValorCreditoTroca.setValue(0f);
                        MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null, "NÃO FOI POSSÍVEL REGISTRAR A TROCA", "DIGITAR TROCA");
                    }  
                }
            }
            */
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    private boolean PesquisarCodigoTroca_Acao(){
        try {            
            
            Long CodigoTrocaDigitada = 0l;//FormatarNumero.FormatarNumeroLong(txtCodigoTroca.getText());
            
            if(CodigoTrocaDigitada!=null){
                ResultSet rs= Troca.TrocasRealizadas(false, CodigoTrocaDigitada);
                if(rs.next()){  
                   Long CodigoVendaTrocaDigitada = TratamentoNulos.getTratarLong().Tratar(rs.getLong("codigovendacreditada"),0l);
                   if(CodigoVendaTrocaDigitada>0l){
                      MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "A TROCA INFORMADA JÁ FOI UTILIZADA NA VENDA ["+ CodigoVendaTrocaDigitada +"]", "LOCALIZAR TROCA");
                      return false;
                   }
                   
                   
                   Double CreditoTrocaDigitada = Troca.ValorTotalCreditoTroca_PorID(CodigoTrocaDigitada);
                   String DadosCliente = 
                           TratamentoNulos.getTratarString().Tratar(rs.getString("idcliente"),"") 
                           + " " ;
                          TratamentoNulos.getTratarString().Tratar(rs.getString("nomecliente"),"") ;
                   if(CreditoTrocaDigitada>0f){
                       String MSG_AO_Operador = (DadosCliente.trim().length()>0 ? "DADOS DO CLIENTE : " + DadosCliente.trim()  +"\n" : "") +
                                                 "VALOR DA TROCA R$ : " + FormatarNumeros.FormatarParaMoeda(CreditoTrocaDigitada)+
                                                 "\n\nCONFIRMA A TROCA ?";
                       
                      if(MetodosUI_Auxiliares_1.MensagemAoUsuarioOpcoes_Sim_e_Nao(null, MSG_AO_Operador, "TROCA LOCALIZADA")==MetodosUI_Auxiliares_1.Sim()){                             
                            //if(Troca.VincularTrocaAVenda(CodigoTrocaDigitada, this.CodigoVenda)){
                                if(VendaEmEdicao.RegistrarVendaEmEdicao_AtualizarDados(this.CodigoVenda, null, null, null, null, null, CreditoTrocaDigitada, CodigoTrocaDigitada,null,null,null,null)){
                                    this.CodigoTroca = CodigoTrocaDigitada;
                                    this.CreditoTroca = CreditoTrocaDigitada;
                                    return true;
                               }
                           // }
                      }
                   }else{
                      MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "CÓDIGO DE TROCA INFORMADA NÃO POSSUI CRÉDITO", "LOCALIZAR TROCA"); 
                   }
                }else{
                   MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "CÓDIGO DE TROCA NÃO LOCALIZADO", "LOCALIZAR TROCA");
                }                
            }else{
                MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "INFORME UM CÓDIGO VÁLIDO", "LOCALIZAR TROCA");
            }
            //return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            
        }
        return false;
    }    /*
      if(txtCodigoTroca.isEditable()){
            PesquisarCodigoTroca();
        }
     */private boolean CancelarTroca(){
        try {
            return Troca.ExcluirTroca(CodigoVenda);
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    private void btCancelarTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarTrocaActionPerformed
        // TODO add your handling code here:
        if(!btCancelarTroca.isVisible()){
            return;
        }
        if(PreVenda){
            MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "Esta troca somente poderá ser cancelada através da PRE-VENDA/COTAÇÃO", "PRÉ-VENDA COM TROCA");
            return;
        }
            
        if(this.CodigoTroca>0l){
            if(MetodosUI_Auxiliares_1.MensagemAoUsuarioOpcoes_Sim_e_Nao(null, "CONFIRMA A EXCLUSÃO DA TROCA ?", "EXCLUIR TROCA")==MetodosUI_Auxiliares_1.Sim()){            
                    if(CancelarTroca()){
                        VendaEmEdicao.RegistrarVendaEmEdicao_AtualizarDados(this.CodigoVenda, null, null, null, null, null, 0d, 0l,null,null,null,null,null,true);
                        //DAO_RepositorioLocal.Commitar_Statment();
                        this.CodigoTroca=0l;
                        this.CreditoTroca=0d;
                        //AtualizarCamposUI();
                        TrocaOK=true;
                        dispose();
                       // btGravarDescontoActionPerformed(evt);
                    }else{
                        MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "NÃO FOI POSSÍVEL EXCLUIR A TROCA", "EXCLUR TROCA");
                    }
                }
        }
      
    }//GEN-LAST:event_btCancelarTrocaActionPerformed

    private void btGravarDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btGravarDescontoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n'){
            btGravarDescontoActionPerformed(null);
        }
    }//GEN-LAST:event_btGravarDescontoKeyPressed

    private void btGravarDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarDescontoActionPerformed
        //dispose();
        // TODO add your handling code here:
        try {

            

            dispose();

        } catch (Exception e) {
            LogDinnamus.Log(e, true);

        }
    }//GEN-LAST:event_btGravarDescontoActionPerformed

    public boolean AtualizarCamposUI(){
        try {           
            txtValorCreditoTroca.setValue(this.CreditoTroca);
            //txtCodigoTroca.setEditable(CodigoTroca.floatValue()==0f ?true: false);
            //txtCodigoTroca.setText(CodigoTroca.toString());
            setValorFinal();
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    
    public boolean IniciarUI(){
        try {            
            //txtValorVenda.setValue(ValorVendaPDV);
            //ZerarCampos();
            //AtualizarCamposUI();           
            Action[] acoes = new Action[4];   
            acoes[0]= new  AbstractAction() {
                @Override  
                public void actionPerformed(ActionEvent e) {
                        btFechar2ActionPerformed(null);
                }
            };                        
             acoes[1]= new  AbstractAction() {
                @Override  
                public void actionPerformed(ActionEvent e) {
                        btTrocaActionPerformed(null);
                }
            };       
              acoes[2]= new  AbstractAction() {
                @Override  
                public void actionPerformed(ActionEvent e) {                    
                   // txtCodigoTroca.requestFocus();
                    //SwingUtilidade.SelectAll(txtCodigoTroca);
                }
            };  
            acoes[3]= new  AbstractAction() {
                @Override  
                public void actionPerformed(ActionEvent e) {                    
                    btCancelarTrocaActionPerformed(e);
                }
            };  
            String[] Teclas = new String[4];            
            Teclas[0] = "ESCAPE";            
            Teclas[1] = "F5";            
            Teclas[2] = "F4";      
            Teclas[3] = "F6";  
            TeclasDeAtalho.DefinirFuncao_A_Tecla_2(PainelPrincipal, acoes, Teclas);            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBotoesTroca;
    private javax.swing.JPanel PainelCorpo;
    private javax.swing.JPanel PainelCreditoTroca;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTopo;
    private javax.swing.JButton btCancelarTroca;
    private javax.swing.JButton btFechar2;
    private javax.swing.JButton btGravarDesconto;
    private javax.swing.JButton btTroca;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JFormattedTextField txtValorCreditoTroca;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nDescontoLiberado
     */
     

    /**
     * @param nDescontoLiberado the nDescontoLiberado to set
     */
     
}

