/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dinnamus.ui.InteracaoUsuario.Venda;

import br.String.ManipulacaoString;
import br.diversos.ControlarDigitacao;
import br.com.info.Sistema;
import br.com.log.LogDinnamus;
import br.com.ui.MetodosUI_Auxiliares_1;
import br.data.ManipularData;
import br.ui.teclas.DefinirAtalhos2;
import br.ui.teclas.controleteclas;
import br.valor.formatar.FormatarNumero;
import com.toedter.calendar.JDateChooser;
import MetodosDeNegocio.Venda.PreVenda;
import MetodosDeNegocio.Venda.PreVendasSelecionadas;
import MetodosDeNegocio.Venda.ParametrosGlobais;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Fernando
 */
public class frmPDV_Simples_ImportarPrevenda extends javax.swing.JDialog {

    /**
     * Creates new form frmPDV_Simples_ImportarPrevenda
     */
    private boolean CarregouUI =false;
    private boolean MesclagemEmAndamento = false;
    private boolean ModificouMesclagem = false;
    public frmPDV_Simples_ImportarPrevenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CarregouUI=IniciarUI();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        chkOperacaoConcomitante = new javax.swing.JCheckBox();
        PainelPrincipal = new javax.swing.JPanel();
        PainelTopo = new javax.swing.JPanel();
        btFechar2 = new javax.swing.JButton();
        lblNomeForma2 = new javax.swing.JLabel();
        PainelCorpo = new javax.swing.JPanel();
        PainelMesclagem = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dbgMesclagem = new br.com.ui.JTableDinnamuS();
        PainelMesclagemBotoes = new javax.swing.JPanel();
        btCancelarMesclagem = new javax.swing.JButton();
        btRemoverPreVenda = new javax.swing.JButton();
        btAdicionarSelecionadas = new javax.swing.JButton();
        btConfirmaMesclagem = new javax.swing.JButton();
        PainelCorpoPreVendas = new javax.swing.JPanel();
        dbgPreVenda = new br.com.ui.JTableDinnamuS();
        PainelCampos = new javax.swing.JPanel();
        PainelCamposPesquisar = new javax.swing.JPanel();
        txtCodigoCotacao = new javax.swing.JTextField();
        txtCodigoOrcamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PainelFiltro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDataInicial = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        txtDataFinal = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        btEscolherPreVenda = new javax.swing.JButton();
        btMesclagem = new javax.swing.JButton();

        chkOperacaoConcomitante.setBackground(new java.awt.Color(255, 255, 255));
        chkOperacaoConcomitante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkOperacaoConcomitante.setMnemonic('O');
        chkOperacaoConcomitante.setText("CONCOMITANTE - [ F2 ]");
        chkOperacaoConcomitante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkOperacaoConcomitante.setOpaque(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        PainelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        PainelPrincipal.setLayout(new java.awt.GridBagLayout());

        PainelTopo.setBackground(new java.awt.Color(0, 0, 0));
        PainelTopo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        PainelTopo.setLayout(new java.awt.GridBagLayout());

        btFechar2.setBackground(new java.awt.Color(0, 0, 0));
        btFechar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btFechar2.setForeground(new java.awt.Color(255, 255, 255));
        btFechar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Shut down_16x16.png"))); // NOI18N
        btFechar2.setMnemonic('x');
        btFechar2.setText("FECHAR");
        btFechar2.setToolTipText("");
        btFechar2.setBorderPainted(false);
        btFechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechar2ActionPerformed(evt);
            }
        });
        btFechar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btFechar2KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelTopo.add(btFechar2, gridBagConstraints);

        lblNomeForma2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNomeForma2.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeForma2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeForma2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/impressora.png"))); // NOI18N
        lblNomeForma2.setText("PDV - IMPORTAR PRÉ-VENDA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        PainelTopo.add(lblNomeForma2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 4, 3);
        PainelPrincipal.add(PainelTopo, gridBagConstraints);

        PainelCorpo.setBackground(new java.awt.Color(0, 0, 0));
        PainelCorpo.setOpaque(false);
        PainelCorpo.setLayout(new java.awt.GridBagLayout());

        PainelMesclagem.setBackground(new java.awt.Color(255, 255, 204));
        PainelMesclagem.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        PainelMesclagem.setForeground(new java.awt.Color(255, 255, 255));
        PainelMesclagem.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MESCLAGEM - PRE-VENDAS SELECIONADAS");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        PainelMesclagem.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PainelMesclagem.add(dbgMesclagem, gridBagConstraints);

        PainelMesclagemBotoes.setBackground(new java.awt.Color(0, 0, 0));
        PainelMesclagemBotoes.setLayout(new java.awt.GridBagLayout());

        btCancelarMesclagem.setBackground(new java.awt.Color(0, 0, 0));
        btCancelarMesclagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCancelarMesclagem.setForeground(new java.awt.Color(255, 255, 255));
        btCancelarMesclagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Close.png"))); // NOI18N
        btCancelarMesclagem.setMnemonic('F');
        btCancelarMesclagem.setText("Cancelar Mesclagem - [ F5 ]");
        btCancelarMesclagem.setBorderPainted(false);
        btCancelarMesclagem.setMargin(new java.awt.Insets(0, 0, 0, 4));
        btCancelarMesclagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarMesclagemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        PainelMesclagemBotoes.add(btCancelarMesclagem, gridBagConstraints);

        btRemoverPreVenda.setBackground(new java.awt.Color(0, 0, 0));
        btRemoverPreVenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btRemoverPreVenda.setForeground(new java.awt.Color(255, 255, 255));
        btRemoverPreVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Erase.png"))); // NOI18N
        btRemoverPreVenda.setMnemonic('F');
        btRemoverPreVenda.setText("Remover Pré-Venda - [ F3 ]");
        btRemoverPreVenda.setBorderPainted(false);
        btRemoverPreVenda.setMargin(new java.awt.Insets(0, 0, 0, 4));
        btRemoverPreVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverPreVendaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        PainelMesclagemBotoes.add(btRemoverPreVenda, gridBagConstraints);

        btAdicionarSelecionadas.setBackground(new java.awt.Color(0, 0, 0));
        btAdicionarSelecionadas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAdicionarSelecionadas.setForeground(new java.awt.Color(255, 255, 255));
        btAdicionarSelecionadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Add.png"))); // NOI18N
        btAdicionarSelecionadas.setMnemonic('F');
        btAdicionarSelecionadas.setText("Adicionar Marcadas -  [ F4 ]");
        btAdicionarSelecionadas.setBorderPainted(false);
        btAdicionarSelecionadas.setMargin(new java.awt.Insets(0, 0, 0, 4));
        btAdicionarSelecionadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarSelecionadasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        PainelMesclagemBotoes.add(btAdicionarSelecionadas, gridBagConstraints);

        btConfirmaMesclagem.setBackground(new java.awt.Color(0, 0, 0));
        btConfirmaMesclagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btConfirmaMesclagem.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmaMesclagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Yes.png"))); // NOI18N
        btConfirmaMesclagem.setMnemonic('F');
        btConfirmaMesclagem.setText("CONFIRMAR - [ F9 ]");
        btConfirmaMesclagem.setBorderPainted(false);
        btConfirmaMesclagem.setMargin(new java.awt.Insets(0, 0, 0, 4));
        btConfirmaMesclagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmaMesclagemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        PainelMesclagemBotoes.add(btConfirmaMesclagem, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PainelMesclagem.add(PainelMesclagemBotoes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 9, 8);
        PainelCorpo.add(PainelMesclagem, gridBagConstraints);

        PainelCorpoPreVendas.setBackground(new java.awt.Color(0, 0, 0));
        PainelCorpoPreVendas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PainelCorpoPreVendas.setOpaque(false);
        PainelCorpoPreVendas.setLayout(new java.awt.GridBagLayout());

        dbgPreVenda.setExibirBarra(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 6, 8);
        PainelCorpoPreVendas.add(dbgPreVenda, gridBagConstraints);

        PainelCampos.setBackground(new java.awt.Color(0, 0, 0));
        PainelCampos.setLayout(new java.awt.GridBagLayout());

        PainelCamposPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        PainelCamposPesquisar.setOpaque(false);
        PainelCamposPesquisar.setLayout(new java.awt.GridBagLayout());

        txtCodigoCotacao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtCodigoCotacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoCotacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodigoCotacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoCotacaoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        PainelCamposPesquisar.add(txtCodigoCotacao, gridBagConstraints);

        txtCodigoOrcamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCodigoOrcamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodigoOrcamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoOrcamentoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelCamposPesquisar.add(txtCodigoOrcamento, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEQUÊNCIA");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelCamposPesquisar.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        PainelCampos.add(PainelCamposPesquisar, gridBagConstraints);

        PainelFiltro.setBackground(new java.awt.Color(0, 0, 0));
        PainelFiltro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        PainelFiltro.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERÍODO");
        jLabel2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        PainelFiltro.add(jLabel2, gridBagConstraints);

        txtDataInicial.setBackground(new java.awt.Color(0, 0, 0));
        txtDataInicial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtDataInicial.getDateEditor().getUiComponent().addKeyListener(

            new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {}

                @Override
                public void keyPressed(KeyEvent e) {
                    if(e.getKeyCode()==KeyEvent.VK_ENTER){
                        //txtDataFinal.requestFocus();
                    }
                }
                @Override
                public void keyReleased(KeyEvent e) {}

            }
        );
        txtDataInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataInicialFocusGained(evt);
            }
        });
        txtDataInicial.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDataInicialPropertyChange(evt);
            }
        });
        txtDataInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataInicialKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelFiltro.add(txtDataInicial, gridBagConstraints);

        txtDataFinal.setBackground(new java.awt.Color(0, 0, 0));
        txtDataFinal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtDataInicial.getDateEditor().getUiComponent().addKeyListener(

            new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {}

                @Override
                public void keyPressed(KeyEvent e) {
                    if(e.getKeyCode()==KeyEvent.VK_ENTER){
                        //SwingUtilidade.RequestFocus(txtValorParcela);
                        // btPesquisar.requestFocus();
                    }
                }
                @Override
                public void keyReleased(KeyEvent e) {}

            }
        );
        txtDataFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataFinalFocusGained(evt);
            }
        });
        txtDataFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDataFinalPropertyChange(evt);
            }
        });
        txtDataFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataFinalKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelFiltro.add(txtDataFinal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 6);
        PainelCampos.add(PainelFiltro, gridBagConstraints);

        btEscolherPreVenda.setBackground(new java.awt.Color(0, 0, 0));
        btEscolherPreVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEscolherPreVenda.setForeground(new java.awt.Color(255, 255, 255));
        btEscolherPreVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Yes.png"))); // NOI18N
        btEscolherPreVenda.setText("SELECIONAR - [F9]");
        btEscolherPreVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscolherPreVendaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        PainelCampos.add(btEscolherPreVenda, gridBagConstraints);

        btMesclagem.setBackground(new java.awt.Color(0, 0, 0));
        btMesclagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btMesclagem.setForeground(new java.awt.Color(255, 255, 255));
        btMesclagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/sitemap.png"))); // NOI18N
        btMesclagem.setText("MESCLAR- [F10]");
        btMesclagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMesclagemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 6);
        PainelCampos.add(btMesclagem, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 6, 5);
        PainelCorpoPreVendas.add(PainelCampos, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.4;
        PainelCorpo.add(PainelCorpoPreVendas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PainelPrincipal.add(PainelCorpo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(PainelPrincipal, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean IniciarUI(){
        try {
            PainelMesclagem.setVisible(false);
            ModificouMesclagem=false;
            PainelFiltro.setVisible(true);
            txtDataInicial.setDate(ManipularData.DataAtual());
            txtDataFinal.setDate(ManipularData.DataAtual());
            
            if(!IniciarUI_DbgPrevenda()){
                return false;
            }
            if(!IniciarUI_TeclaAtalho()){
                return false;
            }
            //txtCodigoCotacao.setCaret(new BasicTextUI.BasicCaret().se);
            txtCodigoCotacao.setDocument(new ControlarDigitacao("NUMERICO"));
            txtCodigoOrcamento.setDocument(new ControlarDigitacao("NUMERICO"));
            
            dbgPreVenda.getjTable().requestFocus();
            Long IndiceSeq =PreVenda.VerificarIndiceSequenciamento(Sistema.getLojaAtual());
            txtCodigoOrcamento.setText(IndiceSeq.toString());
            
            txtCodigoCotacao.requestFocus();
            
            if(dbgPreVenda.getTbDinnamuS().getRowCount()>0){
                dbgPreVenda.getjTable().setRowSelectionInterval(0, 0);
            }
            
            
            IniciarUI_DbgMesclagem();
            
            if(PreVendasSelecionadas.getNotasSelecionadas().size()==0){               
               MesclagemEmAndamento=false;
            }else{
               MesclagemEmAndamento=true;
               btEscolherPreVenda.setVisible(false);
               btMesclagem.setVisible(false);
            }
            
            MetodosUI_Auxiliares_1.MaximizarJanelaDeDialogo(this);
           
            controleteclas.SetarTodosOsBotoes(PainelPrincipal);
            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    private boolean IniciarUI_DbgPrevenda_Atualizar(){
            return IniciarUI_DbgPrevenda_Atualizar(null);
    }
    private boolean IniciarUI_DbgPrevenda_Atualizar(ResultSet rs){
        try {
            if(rs==null){
                rs = PreVenda.ListarPreVendas(Sistema.getLojaAtual(), txtDataInicial.getDate(), txtDataFinal.getDate());
            }
           
            
            dbgPreVenda.setRsDados( rs );
            
             if(!PainelMesclagem.isVisible()){                
               dbgPreVenda.OcultarColuna("selecionada");
            }else{
               dbgPreVenda.ExibirColuna("selecionada");
            }
            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
        
    }
     private boolean IniciarUI_DbgMesclagem_Atualizar(){
        try {
            
            String ListaPreVendasSelecionadas =   "" ;
            if(PreVendasSelecionadas.getNotasSelecionadas().size()==0){
               ListaPreVendasSelecionadas="'0'"; 
            }else {
                ListaPreVendasSelecionadas = ManipulacaoString.TransformarListEmStringDelimitada(PreVendasSelecionadas.getNotasSelecionadas(),false,"");
            }
            
            ResultSet rs=  PreVenda.ListarPreVendas(Sistema.getLojaAtual(), txtDataInicial.getDate(), txtDataFinal.getDate(),ListaPreVendasSelecionadas);
           
            dbgMesclagem.setRsDados( rs );
            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
        
    }
    private boolean IniciarUI_DbgMesclagem(){
        try {
              //dbgMesclagem.addClColunas("faturada", "",30,true,true ,javax.swing.SwingConstants.CENTER,new JCheckBox(), "java.lang.Boolean");
              dbgMesclagem.addClColunas("cliente", "CLIENTE",320);                            
              dbgMesclagem.addClColunas("valor", "VALOR",80);
              dbgMesclagem.addClColunas("codigocotacao", "SEQ",150);
              dbgMesclagem.addClColunas("codigoorcamento", "ID",50);              
              dbgMesclagem.addAlinhamentos("valor", SwingConstants.RIGHT);              
              dbgMesclagem.addAlinhamentos("data", SwingConstants.CENTER);              
              dbgMesclagem.addDateFormat("data");
              dbgMesclagem.addNumberFormat("valor");             
              dbgMesclagem.getTbDinnamuS().setModeloUsandoColecao(true);   
              //dbgMesclagem.getjTable().setRowHeight(dbgPreVenda.getjTable().getRowHeight());
              IniciarUI_DbgMesclagem_Atualizar();  
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    private boolean IniciarUI_DbgPrevenda(){
        try {  
              
              //dbgPreVenda = new JTableDinnamuS();
              
              dbgPreVenda.addClColunas("selecionada", "",30,false,true ,javax.swing.SwingConstants.CENTER,new JCheckBox(), "java.lang.Boolean");
              
              dbgPreVenda.addClColunas("cliente", "CLIENTE",320);              
              dbgPreVenda.addClColunas("data", "DATA",80);
              dbgPreVenda.addClColunas("vendedor", "VENDEDOR",200);
              dbgPreVenda.addClColunas("valor", "VALOR",80);
              dbgPreVenda.addClColunas("codigocotacao", "SEQ",150);
              dbgPreVenda.addClColunas("codigoorcamento", "ID",50);              
              dbgPreVenda.addAlinhamentos("valor", SwingConstants.RIGHT);              
              dbgPreVenda.addAlinhamentos("data", SwingConstants.CENTER);              
              dbgPreVenda.addDateFormat("data");
              dbgPreVenda.addNumberFormat("valor");             
              dbgPreVenda.getTbDinnamuS().setModeloUsandoColecao(true);              
              dbgPreVenda.getjTable().setRowHeight(dbgPreVenda.getjTable().getRowHeight()+20);
              
              
              IniciarUI_DbgPrevenda_Atualizar();
              
              
              //dbgPreVenda.getjTable().getColumnModel().getColumn(0).setHeaderRenderer(new MyTableHeaderRenderer() );
              dbgPreVenda.getjTable().addKeyListener( new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {}
                @Override
                public void keyPressed(KeyEvent e) {
                        if(e.getKeyCode()==KeyEvent.VK_ENTER){
                            e.consume();
                            btEscolherPreVendaActionPerformed(null);
                        }else if(e.getKeyCode()==KeyEvent.VK_F2){
                            e.consume();
                            chkOperacaoConcomitante.setSelected(!chkOperacaoConcomitante.isSelected());
                         }else if(e.getKeyCode()==KeyEvent.VK_SPACE){
                             int Linha = dbgPreVenda.getjTable().getSelectedRow();
                             if(Linha>=0){
                                if(dbgPreVenda.getjTable().getSelectedColumn()>0){ 
                                    Boolean ValorColuna = (Boolean) dbgPreVenda.getTbDinnamuS().getValueAt(Linha, 0);
                                    dbgPreVenda.getTbDinnamuS().setValueAt(!ValorColuna, Linha,0);
                                }
                             }
                         }
                }
                @Override
                public void keyReleased(KeyEvent e) {}
                }
              );              
              return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    
    class MyTableHeaderRenderer extends JComboBox implements TableCellRenderer {
         public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int rowIndex, int vColIndex) {
            addItem("item 1");
            addItem("item 2");
            addItem("item 3");
            return this;
          }
      }        
    private void btFechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechar2ActionPerformed
        try {
            if(!MesclagemEmAndamento){
                PreVendasSelecionadas.LimparNotasSelecionadas();
                ParametrosGlobais.setPreVenda_Codigo(new ArrayList<Long>());
            }else{
                if(ModificouMesclagem){
                    MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "AS NOTAS ENVOLVIDAS NA MESCLAGEM \nFORAM MODIFICADAS. CONFIRME OU CANCELE A OPERAÇÃO", "MESCLAGEM EM ANDAMENTO");
                    return;
                }else{
                    ParametrosGlobais.setPreVenda_Codigo(PreVendasSelecionadas.getNotasSelecionadas());
                    ParametrosGlobais.setMesclagem_Alterada(ModificouMesclagem);                    
                }
            }
            dispose();
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }

    }//GEN-LAST:event_btFechar2ActionPerformed
    private boolean ValidarCampos(){
        try {
                Long CodigoCotacao =  FormatarNumero.FormatarNumeroLong(txtCodigoCotacao.getText());                
                Long CodigoOrcamento =  FormatarNumero.FormatarNumeroLong(txtCodigoOrcamento.getText());
                if(CodigoCotacao==null){
                    MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "SEQUENCIA INVÁLIDA", "PRÉ - VENDA");
                    return false;
                }
                
                if(CodigoOrcamento==null){
                    MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "IDENTIFICADOR INVÁLIDO", "PRÉ - VENDA");
                    return false;
                }   
            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
            
        
    private void btFechar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btFechar2KeyPressed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_btFechar2KeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(!CarregouUI){
            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtDataInicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataInicialFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicialFocusGained

    private void txtDataInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataInicialKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtDataInicialKeyPressed

    private void txtDataFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFinalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFinalFocusGained

    private void txtDataFinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataFinalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFinalKeyPressed
    private void Filtrar(){
        try {
            
            if(txtDataInicial.getDate()==null){
               // MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null, "DATA INICIAL INVÁLIDA", "PESQUISAR PRÉ-VENDA");
                return;
            }
            
            if(txtDataFinal.getDate()==null){
                //MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null, "DATA FINAL INVÁLIDA", "PESQUISAR PRÉ-VENDA");
                return;
            }
            
            IniciarUI_DbgPrevenda_Atualizar();
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }       
    private void Funcoes(String Tecla){
        try {
            if(Tecla.equalsIgnoreCase("ESCAPE")){
                btFechar2ActionPerformed(null);
            }else  if(Tecla.equalsIgnoreCase("F10")){                
                btMesclagemActionPerformed(null);
            }else  if(Tecla.equalsIgnoreCase("F9")){    
                if(btEscolherPreVenda.isVisible()){
                    btEscolherPreVendaActionPerformed(null);
                }else{
                    btConfirmaMesclagemActionPerformed(null);
                }
            }else  if(Tecla.equalsIgnoreCase("F4")){
                 btAdicionarSelecionadasActionPerformed(null);
            }else  if(Tecla.equalsIgnoreCase("F5")){
                btCancelarMesclagemActionPerformed(null);
            }else  if(Tecla.equalsIgnoreCase("F3")){
                btRemoverPreVendaActionPerformed(null);
            }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }
     private boolean IniciarUI_TeclaAtalho(){
        try {
            
           
            
            AbstractAction TeclaAtalhos  = new AbstractAction() {
                public void actionPerformed(ActionEvent e) {
                        String Tecla = e.getSource().toString();                
                        Funcoes(Tecla);
                }
            };    
            String Teclas[] ={"F3","F4","F5","F9","F10","ESCAPE"};            
            DefinirAtalhos2.Definir(PainelPrincipal, Teclas, TeclaAtalhos);            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }    
    private void PesquisarPorCodigo(){
            try {         
               if(ValidarCampos()){
                   Long CodigoOnline = 0l;
                   Long CodigoCotacao =  FormatarNumero.FormatarNumeroLong(txtCodigoCotacao.getText());                
                   Long CodigoOrcamento =  FormatarNumero.FormatarNumeroLong(txtCodigoOrcamento.getText());
                   ResultSet rs = PreVenda.LocalizarPreVendas(CodigoCotacao, CodigoOrcamento, Sistema.getLojaAtual());
                   if(rs.next()){
                       CodigoOnline = rs.getLong("codigo");
                   }
                   IniciarUI_DbgPrevenda_Atualizar(rs);
                   
                   if(dbgPreVenda.getTbDinnamuS().getRowCount()>0){
                       if(PainelMesclagem.isVisible()){                           
                          if(!PreVendasSelecionadas.getNotasSelecionadas().contains(CodigoOnline)) {
                             PreVendasSelecionadas.getNotasSelecionadas().add(CodigoOnline);
                             ModificouMesclagem=true;
                             IniciarUI_DbgMesclagem_Atualizar();
                             txtCodigoCotacao.setText("");
                          }else{
                              MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "PRÉ-VENDA JÁ INCLUIDA NA MESCLAGEM", "LOCALIZAR PRÉ-VENDA");
                          }
                       }else{
                          btEscolherPreVenda.requestFocus();
                       }
                   }else{
                       MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "INFORMAÇÃO NÃO LOCALIZADA", "LOCALIZAR PRÉ-VENDA");
                       txtCodigoCotacao.requestFocus();
                   }               
            }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            
        }
    }
    private void txtDataInicialPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDataInicialPropertyChange
        // TODO add your handling code here:
        if(evt.getPropertyName().equalsIgnoreCase("date")&& this.CarregouUI){
           // btPesquisarActionPerformed(null);
         
                Filtrar();
             
        }
        
    }//GEN-LAST:event_txtDataInicialPropertyChange

    private void txtDataFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDataFinalPropertyChange
        // TODO add your handling code here:
        if(evt.getPropertyName().equalsIgnoreCase("date") && this.CarregouUI){
            //btPesquisarActionPerformed(null);
            Filtrar();
        }
    }//GEN-LAST:event_txtDataFinalPropertyChange

    private void btCancelarMesclagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarMesclagemActionPerformed
        // TODO add your handling code here:ru
        try {
            boolean Fechar = false;
            if(MesclagemEmAndamento){
              if(MetodosUI_Auxiliares_1.MensagemAoUsuarioOpcoes_Sim_e_Nao(null, "DESEJA REALMENTE CANCELAR ESTA OPERAÇÃO", "MESCLAGEM EM ANDAMENTO")!=MetodosUI_Auxiliares_1.Sim()){
                return;    
              }else{
                  Fechar=true;
              }
            }                 
            PreVendasSelecionadas.LimparNotasSelecionadas();
            PainelMesclagem.setVisible(false);
            txtCodigoCotacao.requestFocus();
            dbgPreVenda.OcultarColuna("selecionada");  
            btMesclagem.setVisible(true);
            btEscolherPreVenda.setVisible(true);
            if(Fechar){
                dispose();
            }
            txtCodigoCotacao.requestFocus();
            
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        
        
        
        
    }//GEN-LAST:event_btCancelarMesclagemActionPerformed
    
    private void btRemoverPreVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverPreVendaActionPerformed
        // TODO add your handling code here:
        try {
             Long CodigoVenda = dbgMesclagem.getLong("codigo");
             if(CodigoVenda>0){
                 if(PreVendasSelecionadas.getNotasSelecionadas().contains(CodigoVenda)){
                    PreVendasSelecionadas.getNotasSelecionadas().remove(CodigoVenda);
                    ModificouMesclagem = true;
                    IniciarUI_DbgMesclagem_Atualizar();
                 }
             }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_btRemoverPreVendaActionPerformed

    private void btMesclagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMesclagemActionPerformed
        // TODO add your handling code here:
        try {
            btMesclagem.setVisible(false);
            btEscolherPreVenda.setVisible(false);
            
            PainelMesclagem.setVisible(true);
            
            IniciarUI_DbgMesclagem_Atualizar();
            
            dbgPreVenda.ExibirColuna("selecionada");
            
            txtCodigoCotacao.requestFocus();
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_btMesclagemActionPerformed

    private void btAdicionarSelecionadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarSelecionadasActionPerformed
        // TODO add your handling code here:
        try {
                        
            Long Codigo=0l;
            boolean Atualizou = false;
            if(dbgPreVenda.getTbDinnamuS().getRowCount()>0){
                for (int i = 0; i < dbgPreVenda.getjTable().getRowCount(); i++) {
                    Boolean Selecionado = (Boolean)dbgPreVenda.getTbDinnamuS().getValueAt(i, 0);
                    if(Selecionado){
                       Codigo =dbgPreVenda.getTbDinnamuS().getValorCelulaLong("codigo", i);
                       if(!PreVendasSelecionadas.getNotasSelecionadas().contains(Codigo)){
                          PreVendasSelecionadas.getNotasSelecionadas().add(Codigo);
                          ModificouMesclagem =true;
                          Atualizou =true;
                       }
                    }
                }
                if(Atualizou){
                    IniciarUI_DbgMesclagem_Atualizar();
                }
            }
            
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_btAdicionarSelecionadasActionPerformed

    private void btEscolherPreVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscolherPreVendaActionPerformed
        // TODO add your handling code here:
        try {
            int LinhaAtual = dbgPreVenda.getjTable().getSelectedRow();
            if(LinhaAtual>=0){                
                Long CodigoVenda = Long.valueOf(dbgPreVenda.getTbDinnamuS().getValorCelulaLong("codigo",LinhaAtual).toString());
                ParametrosGlobais.getPreVenda_Codigo().add(CodigoVenda);               
                ParametrosGlobais.setPreVenda_Concomitante(chkOperacaoConcomitante.isSelected());
                PreVendasSelecionadas.getNotasSelecionadas().add(CodigoVenda);
                dispose();
            }

        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_btEscolherPreVendaActionPerformed

    private void txtCodigoOrcamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoOrcamentoKeyPressed
        // TODO add your handling code here:
        try {
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                PesquisarPorCodigo();
            }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
                dbgPreVenda.getjTable().requestFocus();
            }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_txtCodigoOrcamentoKeyPressed

    private void txtCodigoCotacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoCotacaoKeyPressed
        // TODO add your handling code here:
        try {
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                PesquisarPorCodigo();
            }else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
                dbgPreVenda.getjTable().requestFocus();
                if(dbgPreVenda.getTbDinnamuS().getRowCount()>0){
                    dbgPreVenda.getjTable().setRowSelectionInterval(0, 0);
                }
            }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_txtCodigoCotacaoKeyPressed

    private void btConfirmaMesclagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmaMesclagemActionPerformed
        // TODO add your handling code here:
        try {
                ArrayList<Long> CodigoPreVenda =new ArrayList<Long>();
                if(PreVendasSelecionadas.getNotasSelecionadas().size()==1){
                   MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "A OPERAÇÃO DE MESCLAGEM EXIGE PELO MENOS 2(DUAS) PRÉ-VENDAS", "MESCLAGEM NÃO AUTORIZADA");
                   return;
                }else if(PreVendasSelecionadas.getNotasSelecionadas().size()>1){
                    ParametrosGlobais.setPreVenda_Codigo(PreVendasSelecionadas.getNotasSelecionadas());   
                    ParametrosGlobais.setMesclagem_Alterada(ModificouMesclagem);
                    dispose();
                }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_btConfirmaMesclagemActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCampos;
    private javax.swing.JPanel PainelCamposPesquisar;
    private javax.swing.JPanel PainelCorpo;
    private javax.swing.JPanel PainelCorpoPreVendas;
    private javax.swing.JPanel PainelFiltro;
    private javax.swing.JPanel PainelMesclagem;
    private javax.swing.JPanel PainelMesclagemBotoes;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTopo;
    private javax.swing.JButton btAdicionarSelecionadas;
    private javax.swing.JButton btCancelarMesclagem;
    private javax.swing.JButton btConfirmaMesclagem;
    private javax.swing.JButton btEscolherPreVenda;
    private javax.swing.JButton btFechar2;
    private javax.swing.JButton btMesclagem;
    private javax.swing.JButton btRemoverPreVenda;
    private javax.swing.JCheckBox chkOperacaoConcomitante;
    private br.com.ui.JTableDinnamuS dbgMesclagem;
    private br.com.ui.JTableDinnamuS dbgPreVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNomeForma2;
    private javax.swing.JTextField txtCodigoCotacao;
    private javax.swing.JTextField txtCodigoOrcamento;
    private com.toedter.calendar.JDateChooser txtDataFinal;
    private com.toedter.calendar.JDateChooser txtDataInicial;
    // End of variables declaration//GEN-END:variables
}
