/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dinnamus.ui.InteracaoUsuario.nfce;

import br.com.log.LogDinnamus;
import br.ui.teclas.DefinirAtalhos;
import dinnamus.ui.InteracaoUsuario.Venda.frmPDV_SimplesFechamento.EnviarNFE_Processar;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractAction;

/**
 *
 * @author Fernando
 */
public class frmEnviarNFCE_PDV extends javax.swing.JDialog {

    /**
     * Creates new form frmEnviarNFCE_PDV
     */
    private EnviarNFE_Processar enviarNFCE;
    private String RetornoEnvio;
    
    private void FecharForm(){
        setVisible(false);
        this.dispose();
    }
    private Thread tarefa;
    public frmEnviarNFCE_PDV(java.awt.Frame parent, boolean modal , final EnviarNFE_Processar enviarNFCE, Long CodigoVenda) {
        super(parent, modal);
        initComponents();           
        TeclasAtalhos_UI();
        
        this.enviarNFCE=enviarNFCE;
        tarefa = (Thread) enviarNFCE;
        btContingencia1.setVisible(false);
        btFechar.setVisible(false);
        btInterromper.setVisible(false);
        
        enviarNFCE.setEncerrarEnvioListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            
                try{
                    
                
                    RetornoEnvio=enviarNFCE.getRetornoEnvio();

                    if(e==null){
                        FecharForm();
                    }else{    
                      String cmd = e.getActionCommand();

                      lblAnimacao.setVisible(false);
                      btInterromper.setVisible(true);

                      lblMensagem.setText("NÃO FOI POSSÍVEL ENVIAR A NFC-e");

                      //if(!enviarNFCE.getEnviarNFCe().getRejeicaoCodigo().isEmpty()){
                      //    lblMensagem.setText(lblMensagem.getText() + "\n\n" + enviarNFCE.getEnviarNFCe().getRejeicaoMensagem() + "(" + enviarNFCE.getEnviarNFCe().getRejeicaoCodigo() + ")");
                      //}

                      btInterromper.setText("F2 - Tentar de Novo"); 
                      if(cmd.equalsIgnoreCase("Nao Enviou-ErroXml") || !enviarNFCE.getEnviarNFCe().getRejeicaoCodigo().isEmpty()){
                        btContingencia1.setVisible(false);  
                      }else{ 
                        btContingencia1.setVisible(true);
                      }
                      btFechar.setVisible(true);
                      btInterromper.setVisible(true);
                      lblDinnamuSPDV.setVisible(false);

                    }
                }catch(Exception ex){
                    LogDinnamus.Log(ex);
                    Atalhos("Escape");
                }
            }
        });
        tarefa.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PainelPrincipal = new javax.swing.JPanel();
        PainelTopo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();
        PainelCorpo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblMensagem = new javax.swing.JTextArea();
        lblAnimacao = new javax.swing.JLabel();
        PainelBotoes = new javax.swing.JPanel();
        btInterromper = new javax.swing.JButton();
        btContingencia1 = new javax.swing.JButton();
        lblDinnamuSPDV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(444, 207));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(444, 207));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PainelPrincipal.setLayout(new java.awt.GridBagLayout());

        PainelTopo.setBackground(new java.awt.Color(0, 0, 0));
        PainelTopo.setForeground(new java.awt.Color(204, 204, 204));
        PainelTopo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/InteracaoUsuario/nfce/logo-nfce-xs.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        PainelTopo.add(lblTitulo, gridBagConstraints);

        btFechar.setBackground(new java.awt.Color(0, 0, 0));
        btFechar.setForeground(new java.awt.Color(255, 255, 255));
        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tef/Padrao/ui/Shut down_16x16.png"))); // NOI18N
        btFechar.setMnemonic('F');
        btFechar.setBorderPainted(false);
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 44, 2, 2);
        PainelTopo.add(btFechar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelPrincipal.add(PainelTopo, gridBagConstraints);

        PainelCorpo.setBackground(new java.awt.Color(255, 255, 255));
        PainelCorpo.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(null);

        lblMensagem.setEditable(false);
        lblMensagem.setColumns(20);
        lblMensagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMensagem.setLineWrap(true);
        lblMensagem.setRows(5);
        lblMensagem.setToolTipText("");
        lblMensagem.setWrapStyleWord(true);
        lblMensagem.setBorder(null);
        jScrollPane1.setViewportView(lblMensagem);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.8;
        PainelCorpo.add(jScrollPane1, gridBagConstraints);

        lblAnimacao.setBackground(new java.awt.Color(255, 255, 255));
        lblAnimacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnimacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ui/carregando.gif"))); // NOI18N
        lblAnimacao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        PainelCorpo.add(lblAnimacao, gridBagConstraints);

        PainelBotoes.setBackground(new java.awt.Color(255, 255, 204));
        PainelBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PainelBotoes.setToolTipText("");
        PainelBotoes.setLayout(new java.awt.GridBagLayout());

        btInterromper.setBackground(new java.awt.Color(0, 0, 0));
        btInterromper.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btInterromper.setForeground(new java.awt.Color(255, 255, 255));
        btInterromper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Refresh.png"))); // NOI18N
        btInterromper.setMnemonic('1');
        btInterromper.setText("F2 - Interromper Envio");
        btInterromper.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btInterromper.setBorderPainted(false);
        btInterromper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInterromperActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PainelBotoes.add(btInterromper, gridBagConstraints);

        btContingencia1.setBackground(new java.awt.Color(0, 0, 0));
        btContingencia1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btContingencia1.setForeground(new java.awt.Color(255, 255, 255));
        btContingencia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Uploadoffline.png"))); // NOI18N
        btContingencia1.setMnemonic('3');
        btContingencia1.setText("F3 - Emitir em Contingência");
        btContingencia1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btContingencia1.setBorderPainted(false);
        btContingencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContingencia1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PainelBotoes.add(btContingencia1, gridBagConstraints);

        lblDinnamuSPDV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDinnamuSPDV.setText("DinnmuS PDV 2.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        PainelBotoes.add(lblDinnamuSPDV, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PainelCorpo.add(PainelBotoes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        PainelPrincipal.add(PainelCorpo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(PainelPrincipal, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInterromperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInterromperActionPerformed
        // TODO add your handling code here:
       
        try {
            if(btInterromper.getText().equalsIgnoreCase("1 - Interromper Envio")){
                lblMensagem.setText("Soliticando interrupção de envio...aguarde");
                //enviarNFCE.setInterrompido(true);
                enviarNFCE.interrupt();               
                //FecharForm();
            }else{
        
                lblAnimacao.setVisible(true);                
                lblMensagem.setText("Enviando NFC-e..... Aguarde");
                btInterromper.setText("1 - Interromper Envio");
                enviarNFCE.setInterromperEnvio(false);
                btContingencia1.setVisible(false);
                btFechar.setVisible(false);
                btInterromper.setVisible(false);
                lblDinnamuSPDV.setVisible(true);
            }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        
       
    }//GEN-LAST:event_btInterromperActionPerformed
   private void Atalhos(String Fonte){
             
            
            if(Fonte.equalsIgnoreCase("ESCAPE")){
                btFecharActionPerformed(null);
            }else if(Fonte.equalsIgnoreCase("F2")){
                 btInterromperActionPerformed(null);
            }else if(Fonte.equalsIgnoreCase("F3")){
                btContingencia1ActionPerformed(null);
              
            }
   }
    private boolean TeclasAtalhos_UI(){
        try {  
             AbstractAction TeclaAtalhos  = new AbstractAction() {
                public void actionPerformed(ActionEvent e) {
                       String Fonte = e.getSource().toString();                
                       Atalhos(Fonte);
                }
            };            
            DefinirAtalhos.Definir(PainelPrincipal, TeclaAtalhos);
            return true;
       } catch (Exception e) {
           LogDinnamus.Log(e, true);
           return false;
       }
   }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
        //MetodosUI_Auxiliares.CentrarJDialog(this, this.getToolkit());
    }//GEN-LAST:event_formWindowOpened

    private void btContingencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContingencia1ActionPerformed
        // TODO add your handling code here:
      
        try {
            if(!btContingencia1.isVisible()){return;}
            lblAnimacao.setVisible(true);
            btInterromper.setVisible(false);
            btFechar.setVisible(false);
            lblMensagem.setText("Emitindo NFC-e em CONTINGÊNCIA..... Aguarde");
            btInterromper.setText("1 - Interromper Envio");
            enviarNFCE.setInterromperEnvio(false);
            enviarNFCE.setEmitirEmContingencia(true);
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
       
    }//GEN-LAST:event_btContingencia1ActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
       
        try {
            if(!btFechar.isVisible()){ return ;}
             enviarNFCE.setExecutarTarefa(false);
             setVisible(false);
             this.dispose();
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
       
       
    }//GEN-LAST:event_btFecharActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelCorpo;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTopo;
    private javax.swing.JButton btContingencia1;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btInterromper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnimacao;
    private javax.swing.JLabel lblDinnamuSPDV;
    public javax.swing.JTextArea lblMensagem;
    public javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
    public String getRetornoEnvio(){
        return RetornoEnvio;
    }
  
}
