/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dinnamus.ui.InteracaoUsuario.nfce;

import MetodosDeNegocio.Seguranca.UsuarioSistema;
import UI.Seguranca.ValidarAcessoAoProcesso;
import br.com.info.Sistema;
import br.com.log.LogDinnamus;
import br.com.repositorio.DAO_RepositorioLocal;
import br.com.servidor.Dao_Jdbc_1;
import br.com.ui.MetodosUI_Auxiliares_1;
import br.data.DataHora;
import br.ui.teclas.DefinirAtalhos2;
import br.ui.teclas.controleteclas;
import com.toedter.calendar.JDateChooser;
import dinnamus.rel.Relatorios;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashMap;
import javax.swing.AbstractAction;

/**
 *
 * @author Fernando
 */
public class frmNFCe_RelatorioParametros extends javax.swing.JDialog {

    /**
     * Creates new form frmNFCe_RelatorioParametros
     */
    public frmNFCe_RelatorioParametros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        IniciarUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        PainelPrincipal = new javax.swing.JPanel();
        PainelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btFechar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PainelBusca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtDataInicial = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        dtDataFinal = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chkInutilizadas = new javax.swing.JCheckBox();
        chkCanceladas = new javax.swing.JCheckBox();
        chkNormal = new javax.swing.JCheckBox();
        chkEnvioCanc = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btExibir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        opServidor = new javax.swing.JRadioButton();
        opLocal = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        PainelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        PainelPrincipal.setLayout(new java.awt.GridBagLayout());

        PainelTitulo.setBackground(new java.awt.Color(255, 255, 204));
        PainelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        PainelTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 204));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/InteracaoUsuario/nfce/logo-nfce-xs.png"))); // NOI18N
        lblTitulo.setText("RELATORIO DE NFC-E EMITIDAS");
        lblTitulo.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PainelTitulo.add(lblTitulo, gridBagConstraints);

        btFechar1.setBackground(new java.awt.Color(255, 255, 204));
        btFechar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btFechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Shut down_16x16.png"))); // NOI18N
        btFechar1.setMnemonic('F');
        btFechar1.setText("FECHAR");
        btFechar1.setBorderPainted(false);
        btFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 10);
        PainelTitulo.add(btFechar1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        PainelTitulo.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        PainelPrincipal.add(PainelTitulo, gridBagConstraints);

        PainelBusca.setBackground(new java.awt.Color(0, 0, 0));
        PainelBusca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        PainelBusca.setForeground(new java.awt.Color(255, 255, 255));
        PainelBusca.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" até ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        PainelBusca.add(jLabel1, gridBagConstraints);

        dtDataInicial.setBackground(new java.awt.Color(255, 255, 255));
        dtDataInicial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        PainelBusca.add(dtDataInicial, gridBagConstraints);

        dtDataFinal.setBackground(new java.awt.Color(255, 255, 255));
        dtDataFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PainelBusca.add(dtDataFinal, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Repositório");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        PainelBusca.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Período de ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        PainelBusca.add(jLabel4, gridBagConstraints);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        chkInutilizadas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkInutilizadas.setForeground(new java.awt.Color(255, 255, 255));
        chkInutilizadas.setSelected(true);
        chkInutilizadas.setText("Inutilizadas");
        chkInutilizadas.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(chkInutilizadas, gridBagConstraints);

        chkCanceladas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkCanceladas.setForeground(new java.awt.Color(255, 255, 255));
        chkCanceladas.setSelected(true);
        chkCanceladas.setText("Canceladas");
        chkCanceladas.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        jPanel1.add(chkCanceladas, gridBagConstraints);

        chkNormal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkNormal.setForeground(new java.awt.Color(255, 255, 255));
        chkNormal.setSelected(true);
        chkNormal.setText("Normal");
        chkNormal.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        jPanel1.add(chkNormal, gridBagConstraints);

        chkEnvioCanc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkEnvioCanc.setForeground(new java.awt.Color(255, 255, 255));
        chkEnvioCanc.setSelected(true);
        chkEnvioCanc.setText("Envio Cancelado");
        chkEnvioCanc.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        jPanel1.add(chkEnvioCanc, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PainelBusca.add(jPanel1, gridBagConstraints);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btExibir.setBackground(new java.awt.Color(0, 0, 0));
        btExibir.setForeground(new java.awt.Color(255, 255, 255));
        btExibir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/View.png"))); // NOI18N
        btExibir.setText("Visualizar");
        btExibir.setBorderPainted(false);
        btExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExibirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 5, 0);
        jPanel2.add(btExibir, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PainelBusca.add(jPanel2, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Situação");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        PainelBusca.add(jLabel6, gridBagConstraints);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        opServidor.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(opServidor);
        opServidor.setForeground(new java.awt.Color(255, 255, 255));
        opServidor.setText("Servidor");
        opServidor.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(opServidor, gridBagConstraints);

        opLocal.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(opLocal);
        opLocal.setForeground(new java.awt.Color(255, 255, 255));
        opLocal.setSelected(true);
        opLocal.setText("Local");
        opLocal.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(opLocal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PainelBusca.add(jPanel3, gridBagConstraints);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PainelBusca.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        PainelPrincipal.add(PainelBusca, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(PainelPrincipal, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean IniciarUI(){
        boolean Ret = false;
        try {
            /*
               Integer nCodigoUsuario = ValidarAcessoAoProcesso.Verificar(null, UsuarioSistema.getIdUsuarioLogado(), "PDV_RESNFCE", Sistema.getLojaAtual(), true, "Resumo de NFC-e");
            if (nCodigoUsuario == 0) {
                MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("Usuário não possui permissão de acesso a este módulo", "Acesso não autorizado");
                return false;
            }*/
            
            controleteclas.UsarTeclaNaTrocaDeCampos(this.getContentPane(),KeyEvent.VK_ENTER);
            controleteclas.SetarTodosOsBotoes(this.getContentPane());  
            IniciarUI_TeclaAtalho();
          
            KeyListener keys = new KeyListener() {

                @Override
                public void keyTyped(KeyEvent e) {}

                @Override
                public void keyPressed(KeyEvent e) {
                    if(e.getKeyCode()==KeyEvent.VK_ESCAPE){
                       Funcoes("ESCAPE");
                    }
                }

                @Override
                public void keyReleased(KeyEvent e) {}
            };
            dtDataInicial.getDateEditor().getUiComponent().addKeyListener(keys);
            dtDataFinal.getDateEditor().getUiComponent().addKeyListener(keys);
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        return Ret;
    }
    private void  Funcoes(String Tecla){
         
        try {
            if(Tecla.equalsIgnoreCase("ESCAPE")){
                btFechar1ActionPerformed(null);
            }
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        
    }
    private boolean IniciarUI_TeclaAtalho(){
        try {
         
            AbstractAction TeclaAtalhos  = new AbstractAction() {
                public void actionPerformed(ActionEvent e) {
                        String Tecla = e.getSource().toString();                
                        Funcoes(Tecla);
                }
            };      
            String Teclas[] ={"ESCAPE"};            
            DefinirAtalhos2.Definir(PainelPrincipal, Teclas, TeclaAtalhos);            
            dtDataInicial.getDateEditor().getUiComponent().requestFocus();
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    } 
    private void btFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechar1ActionPerformed
        // TODO add your handling code here:

        if(!btFechar1.isEnabled()){ return;}
        this.dispose();
    }//GEN-LAST:event_btFechar1ActionPerformed

    private void btExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExibirActionPerformed
        // TODO add your handling code here:
        
        ImprimirRelatorio();
    }//GEN-LAST:event_btExibirActionPerformed
     private void GerarRelatorio( final HashMap parametros){
        boolean Ret = false;
        try {
            MetodosUI_Auxiliares_1.BloquearDesbloquearComponentes(PainelPrincipal, false);
            new Thread("FrmNFCE_GerarRelatorio") {
                @Override
                public void run() { 
                        
                        String Rel = "nfce.jasper";
                        String subRel = "nfce_detalhe.jasper";
                       
                        (new Relatorios()).Gerar("Relatório de NFC-e Emitidas",  Rel,subRel, parametros, opLocal.isSelected() ? DAO_RepositorioLocal.getCnRepLocal() : Dao_Jdbc_1.getConexao().getCNX()  );
                        MetodosUI_Auxiliares_1.BloquearDesbloquearComponentes(PainelPrincipal, true);
                }
            }.start();
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
      
    }
    private boolean ImprimirRelatorio(){
        boolean Ret = false;
        try {                   
           
            if (!DataHora.IsDateValid("dd/MM/yyyy", dtDataInicial.getDate())) {
                MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("Data inicial Inválida", "Parâmetro inválido");
                dtDataInicial.getDateEditor().getUiComponent().requestFocus();
                return false;
            }
            if (!DataHora.IsDateValid("dd/MM/yyyy", dtDataInicial.getDate())) {
                MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("Data final Inválida", "Parâmetro inválido");
                dtDataFinal.getDateEditor().getUiComponent().requestFocus();
                return false;
            }
            if(opServidor.isSelected() && !Sistema.isOnline()){
              MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesINFO("Não será possível acessar o servidor", "SISTEMA OFF-LINE");
              return false;
            }
           HashMap parametros = new HashMap();       
           Date DataInicial= dtDataInicial.getDate();//DataHora.getStringToData("2001-01-01",  "yyyy-MM-dd");
           Date DataFinal = dtDataFinal.getDate();           
           Timestamp tsDataInicial   = DataHora.setHoraTimestamp( DataHora.getData(DataHora.FormatDataPadraoDAO, DataInicial) + " 00:00:00" );
           Timestamp tsDataFinal   = DataHora.setHoraTimestamp( DataHora.getData(DataHora.FormatDataPadraoDAO, DataFinal) + " 23:59:59" );
           
           String Situacao="";
           if(chkNormal.isSelected()){
               Situacao = "NORMAL";
           }
           if(chkCanceladas.isSelected()){
               Situacao = Situacao + " CANCELADA";
           }
           if(chkInutilizadas.isSelected()){
               Situacao = Situacao + " INUTILIZADA";
           }
           
           
            if(chkEnvioCanc.isSelected()){
               Situacao = Situacao + " ENVIO CANC.";
           }
           
           if(Situacao.length()==0){
               MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO("Escolha uma situação", "Parâmetro não informado");
               return false;
           }
           
           parametros.put("DATA_INICIAL", tsDataInicial);
           parametros.put("DATA_FINAL",tsDataFinal);
           parametros.put("SITUACAO", Situacao);
           parametros.put("REPOSITORIO", (opLocal.isSelected() ? "LOCAL": "SERVIDOR")); 
           //parametros.put("DETALHADO",opDetalhado.isSelected());
           
           GerarRelatorio(parametros);
                      
            //InputStream i = new ou
                    
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        return Ret;
    
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBusca;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTitulo;
    private javax.swing.JButton btExibir;
    private javax.swing.JButton btFechar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chkCanceladas;
    private javax.swing.JCheckBox chkEnvioCanc;
    private javax.swing.JCheckBox chkInutilizadas;
    private javax.swing.JCheckBox chkNormal;
    private com.toedter.calendar.JDateChooser dtDataFinal;
    private com.toedter.calendar.JDateChooser dtDataInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton opLocal;
    private javax.swing.JRadioButton opServidor;
    // End of variables declaration//GEN-END:variables
}
