/*
 * frmLogin.java
 *
 * Created on 19 de Setembro de 2008, 10:25
 */

package dinnamus.ui.InteracaoUsuario.Seguranca;

import br.com.info.Sistema;
import br.infraestrurura.inicializacao.VerificarArquivoCFG;
import br.String.Maiusculo;
import br.String.ManipulacaoString;
import br.TratamentoNulo.TratamentoNulos;
import br.ui.teclas.controleteclas;
import MetodosDeNegocio.Seguranca.Login;
import MetodosDeNegocio.Seguranca.UsuarioSistema;
import MetodosDeNegocio.Venda.GerenciarCaixa;
import MetodosDeNegocio.Venda.pdvgerenciar;
import br.com.ui.MetodosUI_Auxiliares_1;
import dinnamus.ui.InteracaoUsuario.Retaguarda.PrincipalRetaguarda;
import dinnamus.ui.InteracaoUsuario.Venda.frmCaixaDisponiveis;
import dinnamus.ui.InteracaoUsuario.frmPrincipal;
//import br.com.ui.controleteclas;
import dinnamus.ui.infraestrutura.frmSelecionarLojaAtual;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author  desenvolvedor
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * @return the TipoInstalacao
     */
    public static String getTipoInstalacao() {
        return TipoInstalacao;
    }

    /**
     * @param aTipoInstalacao the TipoInstalacao to set
     */
    public static void setTipoInstalacao(String aTipoInstalacao) {
        TipoInstalacao = aTipoInstalacao;
    }
    
    /** Creates new form frmLogin */
    private Login l = new Login();
    private static int nTentativas=0;
    private static String TipoInstalacao="";
    public frmLogin() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        
        try {

            ResultSet rsDadosLoja=Sistema.getDadosLojaAtualSistema();
            if(rsDadosLoja!=null){
                setTipoInstalacao(VerificarArquivoCFG.getHmServidores().get("Servidor0").get("TipoInstalacao"));
                lblNomeLoja.setText(Sistema.getLojaAtual() + "-" + ManipulacaoString.Left(rsDadosLoja.getString("Nome"),30) + " : " + getTipoInstalacao() );
                controleteclas.UsarTeclaNaTrocaDeCampos(this.getContentPane(), KeyEvent.VK_ENTER);
                controleteclas.SetarTodosOsBotoes(this.getContentPane());
            }else{
                MetodosUI_Auxiliares_1.MensagemAoUsuarioSimples(null, "A loja atual definida não pode ser acessada. Redefina as configuração do PDV", "Problema com a Loja Atual", "AVISO");
                frmSelecionarLojaAtual workStation=new frmSelecionarLojaAtual(null, true);
                workStation.setLocationRelativeTo(null);
                workStation.setVisible(true);
                System.exit(0);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNomeLoja = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DinnamuS 2.0");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/InteracaoUsuario/DinnamuS.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblNomeLoja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeLoja, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblNomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log-in", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        txtUsuario.setDocument(new Maiusculo());
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        btOk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btOkFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btOkFocusLost(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        btCancelar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btCancelarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btCancelarFocusLost(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblUsuario.setText(" ");

        lblMsg.setBackground(new java.awt.Color(204, 204, 204));
        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblMsg.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha, 0, 0, Short.MAX_VALUE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btCancelar)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed

         txtSenha.setText(txtSenha.getText().replaceAll("'", ""));
         if (l.Logar(txtUsuario.getText().replace("'", ""), txtSenha.getText().replace("'", ""),true)){             
             if(!UsuarioSistema.isUSuarioCaixa())
             {
               // MetodosUI_Auxiliares.MensagemAoUsuarioSimples(this, "Seja bem-vindo " +  l.MensagemUsuario() , "Login-in","INFO");
                new frmCaixaDisponiveis(this, true);
                if(UsuarioSistema.getIdUsuarioLogadoCaixa()==0)
                {
                    MetodosUI_Auxiliares_1.MensagemAoUsuarioSimples(null, "Não foi selecionado nenhum caixa.", "Caixa não selecionado", "AVISO");                    
                }
             }
             else
             {
                try {
                    ResultSet rs = GerenciarCaixa.ListarCaixas(Sistema.getLojaAtual(), 0  ,0, pdvgerenciar.CodigoPDV(),false);
                    if (rs.next()) {        
                        //VERIFICAR SE O OPERADOR LOGADO ESTA VINCULADO AO CAIXA DO PDV LOCAL
                        Integer IdUsuarioAbriuCaixa = TratamentoNulos.getTratarInt().Tratar(rs.getInt("operadorcx"),0);
                        String StatusCaixa = TratamentoNulos.getTratarString().Tratar(rs.getString("status"),"");                        
                        if(StatusCaixa.equalsIgnoreCase("A")){                            
                            if(IdUsuarioAbriuCaixa.intValue()!=UsuarioSistema.getIdUsuarioLogado().intValue()){                                
                               ResultSet rsDadosOpCaixa = Login.DadosUsuario(IdUsuarioAbriuCaixa, false);                               
                               if(rsDadosOpCaixa.next()){
                                  String NomeOpAbriuCaixa = TratamentoNulos.getTratarString().Tratar( rsDadosOpCaixa.getString("nome"),"");
                                  MetodosUI_Auxiliares_1.MensagemAoUsuarioSimples(this, "O CAIXA ESTÁ ABERTO E EXISTE OUTRO USUÁRIO [ " + NomeOpAbriuCaixa  +" ] OPERANDO NELE", "LOGIN NÃO AUTORIZADO", "AVISO");
                                  LimparCampos();
                                  rsDadosOpCaixa.close();
                                  return;
                               }
                            }
                        }
                        //VERIFICAR SE O OPERADOR LOGADO ESTA VINCULADO A OUTRO CAIXA
                        if(Sistema.isOnline()){
                           ResultSet CaixaAbertoPeloOpEmOutroPDV = GerenciarCaixa.ListarCaixas(Sistema.getLojaAtual(),UsuarioSistema.getIdUsuarioLogado() ,0, 0, false); 
                           if(CaixaAbertoPeloOpEmOutroPDV.next()){
                               Integer IDOutroCodCaixa = CaixaAbertoPeloOpEmOutroPDV.getInt("codigo");
                               String NomeOutroCaixa = CaixaAbertoPeloOpEmOutroPDV.getString("nome");
                               String StatusOutroCaixa = CaixaAbertoPeloOpEmOutroPDV.getString("status");                               
                               if(IDOutroCodCaixa.intValue()!=pdvgerenciar.CaixaVinculado() && StatusOutroCaixa.equalsIgnoreCase("A")){
                                   MetodosUI_Auxiliares_1.MensagemAoUsuarioSimples(this, "O OPERADOR ESTA COM CAIXA [ "+ NomeOutroCaixa +" ] ABERTO EM OUTRO PDV ", "LOGIN NÃO AUTORIZADO", "AVISO");
                                   LimparCampos();
                                   CaixaAbertoPeloOpEmOutroPDV.close();
                                   return; 
                               }
                           }
                        }
                        UsuarioSistema.setIdCaixaAtual(rs.getInt("codigo"));
                        rs.close();
                        MetodosUI_Auxiliares_1.MensagemAoUsuarioSimples(this, "Seja bem-vindo " +  l.MensagemUsuario() , "Login-in","INFO");                 
                    }                   
                } catch (SQLException ex) {
                    Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }

             }
             
             this.setVisible(false);
             if(getTipoInstalacao().equalsIgnoreCase("PDV"))
             {
                 //TarefaSincronismo.Iniciar();
                
                 frmPrincipal _frmPrincipal= new frmPrincipal();
                 _frmPrincipal.setVisible(true);
             }
             else
             {
                PrincipalRetaguarda frmPrincipalRetaguarda= (PrincipalRetaguarda) MetodosUI_Auxiliares_1.MaximizarFrame(new PrincipalRetaguarda());
                frmPrincipalRetaguarda.setTitle("DinnamuS 2.0 - Retaguarda");
                frmPrincipalRetaguarda.setVisible(true);

             }
         }
         else
         {
             MetodosUI_Auxiliares_1.MensagemAoUsuarioSimples(this, "Usuário e/ou Senha não localizado(s)", "Acesso Negado","AVISO");
             nTentativas++;
             if (nTentativas==3)
             {
                 MetodosUI_Auxiliares_1.MensagemAoUsuarioSimples(this, "Número de Tentativas excedido. O Sistema será encerrado", "Acesso Negado", "ERROR");
                 System.exit(0);
             }

         }
         
    }//GEN-LAST:event_btOkActionPerformed
 
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.print(evt.getKeyCode());
    }//GEN-LAST:event_formKeyPressed

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        // TODO add your handling code here:
        if(txtUsuario.getText().length()>0)
        {
            txtUsuario.setText(txtUsuario.getText().replaceAll("'", ""));
            if(l.Logar(txtUsuario.getText().toUpperCase()))
            {
                lblUsuario.setText(l.MensagemUsuario());
                lblMsg.setText("");
            }
            else
            {
                txtUsuario.setText("");
                
                txtUsuario.requestFocus();

                //MetodosUI_Auxiliares.MensagemAoUsuario(this, l.MensagemUsuario(),"Login DinnamuS",-1);

                lblMsg.setText(l.MensagemUsuario());
                
            }
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void btOkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btOkFocusGained
        // TODO add your handling code here:
        controleteclas.UsarTeclaNaTrocaDeCampos(this, KeyEvent.VK_TAB);
    }//GEN-LAST:event_btOkFocusGained

    private void btCancelarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btCancelarFocusGained
        // TODO add your handling code here:
        controleteclas.UsarTeclaNaTrocaDeCampos(this, KeyEvent.VK_TAB);
    }//GEN-LAST:event_btCancelarFocusGained

    private void btOkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btOkFocusLost
        // TODO add your handling code here:
        controleteclas.UsarTeclaNaTrocaDeCampos(this, KeyEvent.VK_ENTER);
    }//GEN-LAST:event_btOkFocusLost

    private void btCancelarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btCancelarFocusLost
        // TODO add your handling code here:
        controleteclas.UsarTeclaNaTrocaDeCampos(this, KeyEvent.VK_ENTER);
    }//GEN-LAST:event_btCancelarFocusLost
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblNomeLoja;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void LimparCampos() {
        txtUsuario.setText("");
        lblUsuario.setText("");
        txtSenha.setText("");
        txtUsuario.requestFocus();
    }
    
}
