/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dinnamus.ui.InteracaoUsuario.Template;

/**
 *
 * @author Fernando
 */
public class Topo extends javax.swing.JPanel {

    /**
     * Creates new form Topo
     */
    public Topo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PainelTopo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btCliente1 = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();
        BotaoMenu = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        PainelTopo.setBackground(new java.awt.Color(0, 0, 0));
        PainelTopo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        PainelTopo.setForeground(new java.awt.Color(255, 255, 255));
        PainelTopo.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/barra logo dinnamus.JPG"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        PainelTopo.add(jLabel3, gridBagConstraints);

        btCliente1.setBackground(new java.awt.Color(0, 0, 0));
        btCliente1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCliente1.setForeground(new java.awt.Color(255, 255, 255));
        btCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/Shut down_16x16.png"))); // NOI18N
        btCliente1.setMnemonic('F');
        btCliente1.setText("Sair");
        btCliente1.setBorderPainted(false);
        btCliente1.setMargin(new java.awt.Insets(0, 0, 0, 4));
        btCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCliente1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        PainelTopo.add(btCliente1, gridBagConstraints);

        lbltitulo.setBackground(new java.awt.Color(255, 255, 204));
        lbltitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltitulo.setText("AUTOMAÇÃO - [ PRINCIPAL ]");
        lbltitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 1, true));
        lbltitulo.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PainelTopo.add(lbltitulo, gridBagConstraints);

        BotaoMenu.setBackground(new java.awt.Color(0, 0, 0));
        BotaoMenu.setForeground(new java.awt.Color(255, 255, 255));
        BotaoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dinnamus/ui/img/dinnamus.png"))); // NOI18N
        BotaoMenu.setBorderPainted(false);
        BotaoMenu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotaoMenu.setOpaque(false);
        BotaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMenuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PainelTopo.add(BotaoMenu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(PainelTopo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCliente1ActionPerformed
        // TODO add your handling code here:
        //Sair();
        //menuSairActionPerformed(null);
    }//GEN-LAST:event_btCliente1ActionPerformed

    private void BotaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMenuActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_BotaoMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoMenu;
    private javax.swing.JPanel PainelTopo;
    private javax.swing.JButton btCliente1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbltitulo;
    // End of variables declaration//GEN-END:variables
}
